### ISSUE TITLE
MouseEvent exist after switching states

### ISSUE THREAD

**Issue by mklee** [AdamAtomic/flixel#1]
Because of the new way mouse callback functions are handled (using the Flash eventlistener) in FlxButton mouse events exist even after the current FlxState has been destroyed. I've modified the code to remove the event listener by adding an empty destroy function in FlxCore which FlxButton overrides.

**Comment by AdamAtomic** [comment]
That's a good idea, that should go in to the master branch for v1.4, maybe tomorrow or friday :)

**Comment by mklee** [comment]
Thanks Adam, looking forward to it!

**Comment by AdamAtomic** [comment]
This SHOULD be working as of 1.34, would love for other people to test it and verify!
