### ISSUE TITLE
FlxTilemap feature requests

### ISSUE THREAD

**Issue by Wiering** [AdamAtomic/flixel#10]
Hi, here are a few suggestions I'd like to make for FlxTilemap:
- getTile() function.
- support for non-square tiles, width and height instead of size (for example, my game Charlie the Duck uses tiles of 20x16 pixels).
- when reading maps, allow the value -1 (or 0xffffffff) for empty/nothing, or... use Int values when comparing with CollisionIndex and DrawIndex, or even better... add a base / skip value that says what number the first tile in your tileset should be (by default 0, but I would normally set this to the same value as DrawIndex). That way you wouldn't have to add dummy tiles at the beginning of your tileset and it would make it easier to use output from Tile Studio).
- option to have the entire map be repeated horizontally and/or vertically (this is very useful for background layers where you make one screen and let it repeat).

**Comment by AdamAtomic** [comment]
Ok there are nice getTile() functions now, non-square tile support, and the recent updates from a week or two ago should help a lot with the collision index/drawindex stuff.  I'm gonna put repeating/tiling the background en totale on the 2.0 wishlist, that could definitely be handy but i'm not up to the mod math and API exposure required to do it elegantly right now :)
