### ISSUE TITLE
[2.35] Truncating angle to int results in a wrong rotation frame for baked rotation

### ISSUE THREAD

**Issue by goshki** [AdamAtomic/flixel#100]
This problem is a residue of issue 46. When truncating the minimally negative angle (say -0.01) to integer (which is essentialy flooring) instead of rounding results in a wrong rotation chosen. Common sense tells that a frame for 0 degree rotation should be chosen but instead we get a -5 degree rotation frame instead.

Oh, by the way - it's the 100th issue! :D

**Comment by AdamAtomic** [comment]
truncation shouldn't happen on negative angles anymore as of 2.20 or so, let me know if this is still a problem in v2.50 though!

**Comment by goshki** [comment]
I've just checked with v2.50 and I'm afraid the problem is still there. Maybe the description is a bit too vague, so... let's say a do something like this:

``` as
loadRotatedGraphic( AssetManager.ImgPlayerBig, 8 );
```

That means I have 8 rotations in 360 degrees, so one rotation frame for every 45 degrees. So I have frame 0 for angle 0, frame 1 for angle 45, frame 2 for angle 90, etc. And in negative angles I have frame 7 for angle -45, frame 6 for angle -90, etc. Now, let's say that my sprite has angle 0, then I have frame 0 playing. All right. I can increase the angle but the frame will remain 0 until I get to angle 45. But if I'm at angle 0 and I decrease the angle even by 0.1, then BOOM! I'm at frame 7 for angle -45 instantly. And it doesn't matter if the angle is -0.01 or -10 or -44.9, I get frame 7.

The common sense tells me that if I have 8 frames every 45 degrees each, then frame 0 should be visible for angles in range [-22.5,22.5], frame 1 for angles in range [22.5,67.5], frame 2 for angles in range [67.5,112.5] and so on. And on the negative end it should be frame 7 for angles in range [-67.5,-22.5], frame 6 for angles in range [-67.5,-112.5], etc.

This problem is especially visible when drawing a rotating Box2D shape with a prerotated Flixel sprite.

**Comment by goshki** [comment]
It should say: "frame 7 for angles in range [-22.5,-67.5]" at the end of the second paragraph.

**Comment by AdamAtomic** [comment]
gotcha - weirdness, I'll check it out!

**Comment by AdamAtomic** [comment]
ahahaha you know how to fix this?  le sigh.  I had to add ONLY a "+ 0.5" to the end of the divide operation.  Now rotations both positive and negative are rounded just how you'd expect :) love the easy ones!!

**Comment by goshki** [comment]
Excellent! Thank you, dear sir. :-)
