### ISSUE TITLE
FlxTilemap.overlaps() should take into account FlxSprites' offsets.

### ISSUE THREAD

**Issue by GregoryAveryWeir** [AdamAtomic/flixel#101]
When you do a FlxTilemap.overlaps(), it ignores FlxSprites' offsets when calculating its ix and iy.  This results in unreliable behavior.  ix and iy should be set with something like the following:

```
        if (Core is FlxSprite)
        {
            ix = Math.floor((Core.x - FlxSprite(Core).offset.x - x) / _tileWidth);
            iy = Math.floor((Core.y - FlxSprite(Core).offset.y - y) / _tileHeight);
        }
        else
        {
            ix = Math.floor((Core.x - x) / _tileWidth);
            iy = Math.floor((Core.y - y) / _tileHeight);
        }
```

**Comment by clayton-grey** [comment]
This seems only partially correct as it doesn't account for FlxSprite offsets either. The whole method could use some love.

**Comment by AdamAtomic** [comment]
yea that stuff was a pretty big mess, I apologize.  in the latest dev push things are laid out kinda like this:

objects and anything that extends them only do overlaps() on their object size/shape, NOT their actual image size/shape.  there is a parameter to let you do this check in world space OR screen space (accomodating scroll factors).

anything that extends sprite has access to a new function called pixelOverlapsPoint() which will do a per-pixel point test in screenspace against the current animation frame
