### ISSUE TITLE
Add Security.allowDomain call to FlxKong(2.35)

### ISSUE THREAD

**Issue by Bradicus** [AdamAtomic/flixel#105]
I had to add the line:
Security.allowDomain(api_url);
to line 39 of FlxKong, right before the //Load the API comment
for a kongregate connection to be set up correctly.  This call is documented
in the current version of the kong api docs at:
http://www.kongregate.com/developer_center/docs/loading-the-as3-api
and is probably required to use the FlxKong class with more recent versions of flash.

**Comment by AdamAtomic** [comment]
flxkong is no longer officially supported in flixel
