### ISSUE TITLE
Looped animation doesn't stop - (Flixel v2.43) - solution provided

### ISSUE THREAD

**Issue by HappyTorso** [AdamAtomic/flixel#106]
As per this thread:
http://flixel.org/forums/index.php?topic=1882.0

Setting the Looped parameter to false when calling FlxSprite.addAnimation does not create a non-looping animation.

Apparently the problem is solved by changing code after line 536 of FlxSprite class from:

if(_curAnim.looped)
_curFrame = 0;
finished = true;

to:
if(_curAnim.looped) {
_curFrame = 0;
finished = true;
}

**Comment by AdamAtomic** [comment]
this should be ok now, as updateAnimation checks for curAnim.looped OR !finished before going ahead with an update
