### ISSUE TITLE
Add onUnpause function to FlxStates

### ISSUE THREAD

**Issue by GregoryAveryWeir** [AdamAtomic/flixel#107]
The actual name of the function is up to you, but it would be awesome if FlxG, when the game unpaused, would call an overridable function in FlxState.  This would provide an easy way to resolve the issue I've seen in various games where a sponsor logo is showing and focus is lost, but clicking on the game to restore focus opens a tab with the sponsor's site, losing focus again... and so on until the end of time.

**Comment by AdamAtomic** [comment]
yea focus and pausing have been heavily revisited in v2.50, pause behavior (excpet for focus lost/gained) is entirely up to the developer now
