### ISSUE TITLE
FlxTilemap.follow() should NOT update world bound.

### ISSUE THREAD

**Issue by jagt** [AdamAtomic/flixel#109]
FlxTilemap.follow() calls FlxG.followBounds() to reset follow bound, but by default it set UpdateWorldBounds to true, so that if you call FlxTilemap.follow(2), the invisible tiles will not collide anymore.  
I suppose the camera moving should never affect the game logic and collision. So I think it should not update world bound or it will make many people confusing about why the invisible tiles just would not collide anymore.

**Comment by AdamAtomic** [comment]
in v2.50 follow() has a parameter for UpdateWorld which you can set to false to prevent this now
