### ISSUE TITLE
FlxTilemap should only overlap colliding tiles.

### ISSUE THREAD

**Issue by GregoryAveryWeir** [AdamAtomic/flixel#11]
It'd be cool if one of two things would happen:
- FlxTilemap.overlaps() would only return "true" if the argument overlapped a colliding tile
- FlxTilemap got a function called something like overlapsCollidingTile() that does the above.

As it is, overlaps() returns true if the argument overlaps _the entire tilemap,_ which isn't all that useful.

**Comment by AdamAtomic** [comment]
ok overrode FlxTilemap.overlaps() to return true only if you are touching collision tiles!  uploading soon
