### ISSUE TITLE
DOCS: FlxLayer is not in the "All Classes" list

### ISSUE THREAD

**Issue by ravenx99** [AdamAtomic/flixel#110]
http://flixel.org/docs/org/flixel/FlxLayer.html exists, but FlxLayer is not listed in the "All Classes" list nor in the index.

**Comment by BillyWM** [comment]
That's just left from the old docs. FlxLayer no longer exists in the 2.x branch, and is now FlxGroup

**Comment by ravenx99** [comment]
Yeah, I just figured that out... but there are two references to FlxLayer in the current docs, which is why I was confused by it.
