### ISSUE TITLE
FlxSound playing field does not correctly update when enigne is paused while sound is playing

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#111]
When the game engine is paused while a sound is playing, that sound's SOUND_COMPLETE event doesn't get hooked back up when the engine is un-paused and thus the 'playing' field incorrectly indicates that the sound is still playing.

in the play() function line 188 excerpt:

else
{
        _channel = _sound.play(_position,0,_transform);
        if(_channel == null)
                active = false;
}

should be:
else
{
    _channel = _sound.play(_position,0,_transform);
    if(_channel == null)
        active = false;
    else
        _channel.addEventListener(Event.SOUND_COMPLETE, looped);
}

**Comment by AdamAtomic** [comment]
yea i don't strip the sound_complete event on pause anymore, so i think this should be alright!
