### ISSUE TITLE
FlxSound does not add back event listener upon resume from pause

### ISSUE THREAD

**Issue by mrpatte** [AdamAtomic/flixel#112]
The play function in FlxSound does not add the event listener for sound completion if the sound is not looping and is not in the starting position. The listener is removed in pause. This causes replay issues in none looping sounds that have been paused then played to completion. A fix would be to add the event listener back in play as shown:
    public function play():void
        {
            if(_position < 0)
                return;
            if(_looped)
            {
                if(_position == 0)
                {
                    if(_channel == null)
                        _channel = _sound.play(0,9999,_transform);
                    if(_channel == null)
                        active = false;
                }
                else
                {
                    _channel = _sound.play(_position,0,_transform);
                    if(_channel == null)
                        active = false;
                    else
                        _channel.addEventListener(Event.SOUND_COMPLETE, looped);
                }
            }
            else
            {
                if(_position == 0)
                {
                    if(_channel == null)
                    {
                        _channel = _sound.play(0,0,_transform);
                        if(_channel == null)
                            active = false;
                        else
                            _channel.addEventListener(Event.SOUND_COMPLETE, stopped);
                    }
                }
                else
                {
                    _channel = _sound.play(_position,0,_transform);
                    if(_channel == null)
                        active = false;
                    //added else statement which adds back sound complete event listener
                    else
                        _channel.addEventListener(Event.SOUND_COMPLETE, stopped);
                }
            }

**Comment by ghost** [comment]
This is the same as Issue #111. It looks like we both had the same thought at almost the same time.

**Comment by AdamAtomic** [comment]
i don't think i remove any listeners on pause anymore, hopefuly this is fixed!
