### ISSUE TITLE
FlxU.overlap weird and broken behaviour with tilemap

### ISSUE THREAD

**Issue by Nek** [AdamAtomic/flixel#115]
Hi!
Basically I have a level made with Dame and a custom Bullet class which extends FlxSprite.
I put several bullets in the bullets FlxGroup.
Then I have:
    FlxU.overlap(bullets, level.mainLayer, killBullet);

```
private function killBullet(bullet:FlxObject, tile:FlxObject):void {
  //this one has a breakpoint
}
```

When overlap happens I get a strange result.
The overlay is going on for the tiles with index 0.
The killBullet gets parameters in wrong order so I can see in the debugger that bullet is FlxTilemap and tile is Bullet.
Debugger's screenshot: 
http://cl.ly/461V3g2O3V2R2o0G1Q1i

**Comment by AdamAtomic** [comment]
tilemaps and overlaps should suck waaaay less now

**Comment by Nek** [comment]
wow!! time to get back to experiments!
thanks.
