### ISSUE TITLE
FxSprite is not rendered at its origin

### ISSUE THREAD

**Issue by nsxdavid** [AdamAtomic/flixel#119]
The FlxSprite renderSprite() function does not properly render the sprite at its origin.

This code:
            //Advanced render
            _mtx.identity();
            _mtx.translate(-origin.x,-origin.y);
            _mtx.scale(scale.x,scale.y);
            if(angle != 0)
                _mtx.rotate(angle \* 0.017453293);
            _mtx.translate(_point.x+origin.x,_point.y+origin.y);
            FlxG.buffer.draw(_framePixels,_mtx,null,blend,null,antialiasing);

Should be written:

```
        //Advanced render
        _mtx.identity();
        _mtx.translate(-origin.x,-origin.y);
        _mtx.scale(scale.x,scale.y);
        if(angle != 0)
            _mtx.rotate(angle * 0.017453293);
        _mtx.translate(_point.x,_point.y);  // <<< FIX HERE
        FlxG.buffer.draw(_framePixels,_mtx,null,blend,null,antialiasing);
```

**Comment by AdamAtomic** [comment]
flixel is an upper left corner renderer at the moment, so the existing code is correct i think

**Comment by nsxdavid** [comment]
That makes no sense for sprites.  Imagine a sprite depicting a planet and some child prites depicting beings walking around the outer circumference. Or a zillion other common examples.  You want the position to be the center.

**Comment by AdamAtomic** [comment]
When flixel rolls over to molehill, hopefully later this year, there will probably be more flexible options for the object origin.  In the meantime, the origin simply refers to the point about which scaling and rotation occurs in the sprite, but positioning is done with the upper left corner.  Positioning sprites off their centers by default is just as crazy as positioning them off their upper left corners, I promise!  Supporting both is the best solution, but requires some reorganization, so I'm saving it until I have to do it do get GPU support anyways.

**Comment by nsxdavid** [comment]
The best answer is to be able to set the pivot point.  But lacking that, and in either case, the sane default is the center.  I'd be hard pressed to think of any general case where upper left makes any sense.  For example, int he world of typical game examples: Would rotating a space ship sprite around its upper left make sense to you?

**Comment by AdamAtomic** [comment]
rotation does work around the center of the sprite in flixel, it just doesn't use the midpoint for positioning

**Comment by nsxdavid** [comment]
Hence the bug report. :)

**Comment by fidgetwidget** [comment]
I have to agree with nsxdavid on this one. While forcing the center for position is not any better than forcing the top left for position, having the position being based on the origin is neither. The origin then acts as both the anchor point AND origin point, but unless you want to add an anchor variable for the expressed purpose here I am going to use nsxdavid's suggestion... thanks :D
