### ISSUE TITLE
Problems with FlxSave

### ISSUE THREAD

**Issue by OrpheusTheBard** [AdamAtomic/flixel#12]
Not a bug per se, but I was bewildered today when my project started crashing suddenly at runtime for me, but worked fine for everyone else. Also, it didn't happen when I was testing locally, only when I uploaded it to my server. I finally tracked the problem down to my save and load routines, and I think it turned out to be _some_ problem with the shared object... 

Since I'm new to Flash, I'm not familiar with what it might have been. Maybe I exceeded the maximum size (which I find strange since it hardly reaches 1kb of data and my maximum was set to 100kb at the time). I also didn't get any window asking for permission to allocate more space or anything, just a runtime crash... But allocating some more space manually, and then reverting it back to what it was before, magically solved the problem...

Having this in mind, I think FlxSave should be expanded slightly, so that it adds a bit of more control, specifically so that it informs the user (a boolean return would be sufficient) whether a read or write was successful, and to enable setting a minimum file size (via flush's parameter). This way we could at least handle failures gracefully instead of crashing a bit later on.

**Comment by AdamAtomic** [comment]
THanks for the feedback!  I've updated FlxSave to return booleans and allow you to set a minimum file size too, should be uploaded asap

**Comment by OrpheusTheBard** [comment]
Great :) I read a bit on the matter, and there's two things I'd like to note:
1. Not sure if there's any difference, but the example I saw said that SharedObject.flush throws an exception and returns a String on failure, not a Boolean, so it used a try ... catch instead of comparing it to true.
2. It is also possible for SharedObject.getLocal to throw an exception (such as when the user has disabled third-party shared objects), so I also made a second layer of protection there by adding a boolean property "valid" to the class, catching any exception thrown by getLocal on the constructor and setting valid to false if anything went wrong. Then any other method that makes use of the shared object, returns right away if the shared object isn't valid in the first place.

**Comment by OrpheusTheBard** [comment]
Source: http://www.adobe.com/livedocs/flex/3/langref/flash/net/SharedObject.html

**Comment by OrpheusTheBard** [comment]
And sorry for the triple post, but just noticed:

Shouldn't "MinFileSize:uint=0" also be added to the methods that make use of forceSave (write and erase) ? Because usually forceSave isn't even used directly but rather through the other two methods.

**Comment by AdamAtomic** [comment]
Yea right on both points, I'll upload some tweaks in a few minutes!

**Comment by AdamAtomic** [comment]
Ok pushed up some new codes, you need to call bind() now before you can call write() or read(), Mode has been updated accordingly

**Comment by OrpheusTheBard** [comment]
You're the man :)
