### ISSUE TITLE
FlxGame Width causing TileBlock Collision Issues

### ISSUE THREAD

**Issue by VikramN** [AdamAtomic/flixel#123]
Hi,

I've setup a Tileblock and Sprite to collide. I've set the camera to follow sprite.
But the collision stops happening after the player moves past the FlxGame width.

For Ex:
Collision stops at 400 when "SWF(width="800"..."  & in my game class ctr: super(400, 300, PlayState, 2);

Collision stop at 800 when "SWF(width="800"..."  & in my game class ctr: super(800, 600, PlayState, 1);

I'm using Version 2.35

Sorry I couldn't find any help on this anywhere else - so posting here.

**Comment by VikramN** [comment]
Update #1:
Collision seems to work when I use Tilemap and only if i call "follow" on it. Is it that bounds don't move when Tilemap is not following but only the player??

**Comment by AdamAtomic** [comment]
yeap, you gotta set the FlxG.worldBounds in v2.50 to include the whole tilemap.  There is an extra tilemap helper called getBounds() or something that can help with that too!
