### ISSUE TITLE
First Tile from FlxTileMap.pngToCSV() never gets filled

### ISSUE THREAD

**Issue by KWarp** [AdamAtomic/flixel#127]
Found in flixel 2.35

There is an issue where the tile at position (0, 0) in the upper-left corner would never be filled. 

_Solution:_
I took a dump of a pngToCSV string and found that it's first character value was always null. It appears that the += operator does funny things to null strings. 

_Instead of:_
var csv:String;

_Do:_
var csv:String = "";

**Comment by AdamAtomic** [comment]
awesome, i'm on it :)
