### ISSUE TITLE
When FlxTileMap auto is OFF, cannot setTile() with Tile id of 0

### ISSUE THREAD

**Issue by KWarp** [AdamAtomic/flixel#128]
found in Flixel 2.35

I am manually assigning tiles using the FlxTileMap.setTile() function based on data from an external XML file made in the Ogmo Editor, 
When FlxTileMap auto is OFF, I cannot manually assign tiles an identifier of zero. Example:

var Tile:uint = 0
tileMap.setTile(someX, someY, Tile, true);

Result: anything with a Tile value of 0 _does not draw._
Anything with a value of 1 or greater works fine,

A Tile value of 0 matters because it is the first image in a tileset image.

My hack solution was the following:

protected function updateTile(Index:uint, forceDraw:Boolean=false):void
        {
            if(_data[Index] < drawIndex && !forceDraw)
            {
                _rects[Index] = null;
                return;
            }
           // no further changes in this function
}

// in the function setTileByIndex
        if(auto == OFF)
    {
        updateTile(Index, true);
        return ok;
    }

**Comment by AdamAtomic** [comment]
you can set that, you just have to mess with either hte starting index or the visible index.  this stuff is easier to work with in v2.50 though!

**Comment by KWarp** [comment]
I didn't have much luck with startingIndex and visibleIndex.

startingIndex = visibleIndex = 0; 
would fill all the empty tiles with the first tile in the set

startingIndex = visibleIndex = 1; 
would shift every tile in my set over by 1

If 2.5 has it working better, maybe I'll upgrade once it's out of beta.

**Comment by AdamAtomic** [comment]
yea i'm not sure how else it could even work though, right?  if you want to set tiles to be able to be "0", and be drawn, then visibleIndex aat least would have to be 1.

however, in the new stuff, you have a LOT more control over how tile types behave, so i think it'd be worth checking out at least
