### ISSUE TITLE
FlxG.elapsed not increased

### ISSUE THREAD

**Issue by bengsiswantoh** [AdamAtomic/flixel#133]
Hi Adam,
I'm using flixel v2.5. When i trace FlxG.elapsed stack at 0.016. is it bug or not?

**Comment by goshki** [comment]
FlxG.elapsed holds the number of elapsed seconds since last frame (16 milliseconds in your case) not since the start of the game. If it was increasing that would mean that your framerate drops continuously. :-)

**Comment by bengsiswantoh** [comment]
ow thanks for your reply goshki
