### ISSUE TITLE
FlxTimer Suggestions

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#134]
In FlxTimer there does not seem to be an easy way to create a timer with an infinite amount of loops, for example, if you wanted the player to gain an extra life every 30 seconds. An easy way to implement this would be to allow a 0 value for loops and in the update method do not increment or do a stop() check if loops is a falsey value. 

Also,  the timeLeft() method is useful but another useful method would be progress() which would return the timeleft as a percentage. Perfect for people who have a graphical bar representing the timer.

```
    public function get progress():Number {
        return _timeCounter/time;
    }   
```

Finally, a little nitpick, I can't think of a single instance  where you'd want to create a timer w/o a callback function. It might make more sense to swap the Callback, and loops parameters in the start() method.

**Comment by AdamAtomic** [comment]
oh - yea infinite loops would be nice, i'll figure something out :)

for timers, if you don't like using callbacks you can also check ".finished" so i think having callbacks be optional does make sense, but it might still make sense to put loops last

**Comment by ghost** [comment]
Thanks for the response,

Some other nitpicks:

For better interface consistency you might wan to make the paused variable read-only and than provide a pause() method to go along with the start() and stop() methods. 

The finished flag should also be readonly as someone might mistakenly think that setting finished = true is the correct way to stop the timer. The worst part is that it would actually work but this way the timermanager would never get properly removed resulting in it calling the timer update every frame. Not a huge deal since the method will instantly return but undesirable.

**Comment by AdamAtomic** [comment]
cool, timers should support infinite loops and the progress getter now :)  i agree with the other suggestions but i don't want to change the master branch API yet

**Comment by ghost** [comment]
Hey thanks,

If you don't mind re-opening the issue I have one more suggestion:

In my game, I like to use FlxTimer for specific roles (like one to recharge mines every 30 seconds, one to recharge shields every x sec, etc). So I call start() on those timers at different parts of my code and what I found to be really helpful was to add default values for the seconds, callback and times parameters in the constructor, that way when I call the start method I don't have to pass those same parameters. It just uses whatever was set in the constructor.

**Comment by ghost** [comment]
constructor:

public function FlxTimer(Time:Number=1,Loops:uint=1,Callback:Function=null)

start:

public function start(Time:Number=NaN,Loops:int=-1,Callback:Function=null):FlxTimer {
....
            time = isNaN(Time) ? time : Time;
            loops = Loops == -1 ? loops : Loops;
            _callback = Callback || _callback;

....
}
