### ISSUE TITLE
useFlixelCursor request.

### ISSUE THREAD

**Issue by UberGeorge** [AdamAtomic/flixel#135]
You currently have a useDefaultHotKeys switch. I'd also like to see a useFlixelCursor switch. If it's set to false Flixel switches to the Flash system cursor instead of it's own.

**Comment by xortive** [comment]
This would be awesome

**Comment by AdamAtomic** [comment]
cool - i added a useSystemCursor switch to FlxGame, which defaults to false.  not sure if it's ideal yet but it should help!
