### ISSUE TITLE
FlxButton sound effects request

### ISSUE THREAD

**Issue by UberGeorge** [AdamAtomic/flixel#137]
Could you add mouseOver and buttonClick sound effects options to FlxButton

**Comment by xortive** [comment]
just have a sound effect play in the callback

**Comment by UberGeorge** [comment]
Well yes, but the point is for it to happen automatically just like the button image changes automatically.
You wouldn't tell someone to change the image in the callback, and button sounds have been a standard feature of game buttons since the dawn of computer games.

**Comment by AdamAtomic** [comment]
k buttons can play sounds now :) when i push up the new master branch later today check out FlxButton.setSounds()
