### ISSUE TITLE
Buttons don't work well with the new camera system

### ISSUE THREAD

**Issue by phmongeau** [AdamAtomic/flixel#139]
If you create a FlxButton out of screen and focus a FlxCamera on it, it shows in the camera view, but doesn't respond to the mouse.

I suspect this is because the cursor is not at the same coordinates than the FlxButton (even though the camera renders them at the same on-screen location)

**Comment by AdamAtomic** [comment]
huh - that's _supposed_ to work fine, i built whole special mouse/camera stuff for that situation... i'll have to check it out!

**Comment by phmongeau** [comment]
hmm...  I just made a new flixel project just to test, and it looks like it works. I guess the bugs comes from somewhere else.

**Comment by phmongeau** [comment]
I think I just found how to reproduce the bug.

If you set the scrollFactor of a button to 0 and display the button in only one camera who isn't centered (like the second camera in the split screen demo), the buttons displays with coordinates relative to the origin point of the camera, but the clickable area is set relatively to the 0,0 point of the screen. So the clickable area is not at the same place as the button graphics.

**Comment by AdamAtomic** [comment]
ooohhh I think I might know what's going on with this.  screenspace checks against certain things may be assuming that the camera is at 0,0... let me see what i can find

**Comment by AdamAtomic** [comment]
ok i was able to just tweak the way the mouse screen position is calculated and it looks like the behavior is much better/more reliable now, will push it out soon!  thanks :)
