### ISSUE TITLE
FrameRecord save() and load() are using different seperators!

### ISSUE THREAD

**Issue by guoboism** [AdamAtomic/flixel#141]
From FrameRecord.save()
~
var output:String = frame+"keyPair";
~

From FrameRecord.load(Data:String)
~
var array:Array = Data.split("k");
~

Keep up good work, man. I am watching your back!

**Comment by AdamAtomic** [comment]
oh jeez you're right, it got find & replaced during my documentation blitz!  fixing and pushing now....
