### ISSUE TITLE
FlxG.getPlugin() skips every other plugin

### ISSUE THREAD

**Issue by axcho** [AdamAtomic/flixel#144]
Currently, FlxTimer does not work. This is because each FlxTimer cannot find the TimerManager plugin. And that is because FlxG.getPlugin() has a typo that causes it to skip every other plugin while searching through the list.

This is because i++ happens twice. Oops.

```
    static public function getPlugin(ClassType:Class):FlxBasic
    {
        var pluginList:Array = FlxG.plugins;
        var i:uint = 0;
        var l:uint = pluginList.length;
        while(i < l)
        {
            if(pluginList[i++] is ClassType)
                return plugins[i];
            i++;
        }
        return null;
    }
```

Might want to take out that first i++, right?

**Comment by AdamAtomic** [comment]
yea that should be fixed on the beta branch already, found it during LD48 :)
