### ISSUE TITLE
Pathfinding Distances offset

### ISSUE THREAD

**Issue by SeiferTim** [AdamAtomic/flixel#145]
It looks like the ComputePathDistance function in FlxTilemap is computing distances incorrectly.
It looks like the Tiles around the start are all set to 0, and the start tile is 1.
This leads to some strange behavior, particularly with walls or collision. What happens is that walkPath puts the last node on one of the 0s around the start, and then the findPath function moves that last node to where the start is - so the first 2 nodes are 2-tiles apart instead of 1, and the pathing object is more likely to clip through a wall it's right next to.
To fix, I changed all instances of:
`distances[index] = distance;`
to 
`distances[index] = distance+1;`
And at the end of the function, right before 
`return distances;`
I added
`distances[StartIndex] = 0;`

**Comment by AdamAtomic** [comment]
ok, put in a similar fix, shoudl be ok in the master branch update later today :)
