### ISSUE TITLE
Pathfinding: findPath using uints to determine exact placement on Tilemap

### ISSUE THREAD

**Issue by SeiferTim** [AdamAtomic/flixel#146]
The findPath function on FlxTilemaps is doing something I didn't realize at first: it's determining the exact placement of the Start and End points based on the position of the tilemap - however, it's using uints, so if the tilemap's positon ever happens to be negative, then the findPath routine doesn't calculate correctly, and causes other stuff to blow up.
I just changed the first few lines of the function to say:
`//figure out what tile we are starting and ending on.
var startIndex:int = int((Start.y-y)/_tileHeight) * widthInTiles + int((Start.x-x)/_tileWidth);
var endIndex:int = int((End.y-y)/_tileHeight) * widthInTiles + int((End.x-x)/_tileWidth);`
Now it calculates properly regardless of the x,y of my Tilemap :P

**Comment by AdamAtomic** [comment]
i think it has to calculate uints for the actual indices, but i changed the internal castings to ints, hopefully that fixes it!  wwill go out in the master branch update later today :)
