### ISSUE TITLE
FlxGroup.getRandom() broken.

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#147]
In FlxGroup:

public function getRandom():FlxBasic{
    return FlxG.getRandom(members) as FlxBasic;
}

FlxG.getRandom(ARRAY) uses the array's length member to determine a range for the random int, but the length param for the "members" array in FlxGroup can't be trusted since it's padded with null values.

**Comment by ghost** [comment]
Here's a quick fix if you want to merge it in:

in FlxGroup:

public function getRandom():FlxBasic
{
   return FlxG.getRandom(members,length) as FlxBasic;
}

in FlxG:

```
    static public function getRandom(Objects:Array, Length:uint = 0):Object
    {
        if(Objects != null)
        {
            var l:uint = Length || Objects.length;
            if(l > 0)
                return Objects[uint(FlxG.random()*l)];
        }
        return null;
    }
```

**Comment by AdamAtomic** [comment]
nice catch!  i beefed up getRandom() to take optional StartIndex and Length parameters, and added those options to FlxGroup as well :)
