### ISSUE TITLE
FlxQuadTree.add() doing unnecessary loops.

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#148]
Trying to debug why my overlaps were not working (I had exists = false set on my group , doh!) , I came across this:

FlxQuadTree.add() starting at line 321.

<code>
 if(ObjectOrGroup is FlxGroup)
{
   var i:uint = 0;
   var basic:FlxBasic;
   var members:Array = (ObjectOrGroup as FlxGroup).members;
   var l:uint = members.length;
   while(i < l) { ...
</code>

Same issue as https://github.com/AdamAtomic/flixel/issues/147
line 326 should read :

var l:uint = FlxGroup(ObjectOrGroup).length;

I did a search for "members.length" to see if its a potential issue anywhere else and I got a hit in FlxG with the sounds variable and in FlxEmitter line 239+240.

**Comment by AdamAtomic** [comment]
good catches!! these fixes will go out in the master branch update later today, thanks :)
