### ISSUE TITLE
Changing position x/y of FlxLayer does not change position of children

### ISSUE THREAD

**Issue by Edcle** [AdamAtomic/flixel#15]
It seems there's a bug when setting the position (x/y) of an FlxLayer. If you try to do this, nothing happens - any sprites, buttons, on the layer don't get moved.

Turns out in FlxLayer.update(), super.update() should be at the end instead of the start of the function, due to the way FlxCore.last is used.

I've made this change locally and it seems fine.

**Comment by AdamAtomic** [comment]
Ah yea, totally right!  Should be fixed in the next push!
