### ISSUE TITLE
Can't collide during overlap callback.

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#150]
This was possible in 2.43, but in 2.5 trying to collide two entities via FlxG.collide during their overlap callback results in an error. The error occurs in FlxQuadTree.overlapNode @ line 572:  _iterator = _iterator.next; 

Error is trying to access property on a null reference.

**Comment by xortive** [comment]
just add FlxObject.separate to your FlxG.overlap call, as the Process Callback. Its what FlxG.collide does.

**Comment by ghost** [comment]
Negative. I don't get the error with seperate but there's no collision response at all.

**Comment by xortive** [comment]
try setting the processcallback to FlxG.Collide

**Comment by ghost** [comment]
I got the null error by doing that. 

it's a bug, Since _iterator is a static member the assumption is made that only one quad tree can be processed a time, and for the most part that is true except for the instances where another quad tree is called during one of the notify or process callbacks.

**Comment by AdamAtomic** [comment]
I'm gonna look into getting the quad trees to be less dependent on being like "only one at a time", but in the meantime, I would avoid using FlxG.collide() when you have just 2 objects, like in a callback like that.  Deviantg33k's initial suggestion is the correct one, to use FlxObject.separate() manually within the callback.  Even if we resolve the quad tree error, all it can do, in the best case scenario, is call FlxObject.separate() on those two objects anyways.

I'll also look into whether the quad tree somehow primes the objects before calling separate(), but I don't believe it does...

**Comment by AdamAtomic** [comment]
yea you can just use FlxObject.separate() manually like Deviantg33k suggested, I just tested here.  It's definitely preferable to setting up an entire new quad tree just to check 2 objects, and as previously stated, all that will do is call FlxObject.separate() on those objects.  Make sure that their allowCollision flags are valid, that they're not both set as "immoveable" etc.

I will look into making quad trees more flexible still, but in this particular situation, its massive overkill and redundant.

**Comment by ghost** [comment]
Ok that makes sense, calling collide within one of the overlap callbacks was definitively wasteful. I'll use seperate from now if I need to do something similar. 

In this particular case it didn't work for me and I debugged a bit and figured out why; I'm checking the collision against the players hitbox (which is just an flxobject that updates its midpoint position to match the players on every update), the hit box is smaller than the player so when the hitbox collides with an enemy there's already a significant overlap between the player and the enemy, I than want to separate the player from the enemy but the separate function does not proceed because of this check:

(overlap > maxOverlap)

I have overlap reporting at 20 px and maxOverlap at about 5, I tired passing in an optional parameter to remove that check but the collision was much jerkier than what I remember it being in 2.43. So I ended up giving up on the seperate as It was there mostly for cosmetic reasons. Maybe I'll import the 2.43 function in there as well to get the behavior that I want.

Thanks.

**Comment by edgarMeetHi** [comment]
What is the solution now? It looks like FlxObject.separate()  was removed.
