### ISSUE TITLE
Changing background color causes graphical error

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#152]
Sorry if I wrote this in the wrong place, I recently updated to the latest Master build of Flixel.

Certain background colors will cause errors with moving sprites. I an image comparing three different backgrounds

http://i.imgur.com/pDa8m.png

**Comment by xortive** [comment]
It's because flixel's color format is AARRGGBB
to prevent graphical errors, make your BG colors have the alpha channel set to FF.

**Comment by ghost** [comment]
Ah thanks Deviantg33k, you fixed my issue =)
