### ISSUE TITLE
The cameras Array of a FlxButton doesn't apply to it's text

### ISSUE THREAD

**Issue by phmongeau** [AdamAtomic/flixel#153]
If I only put one camera in the cameras array of a FlxButton, the label of the buttons still renders on all the cameras.

(A similar bug happens if you modify the scrollFactor of a button after it's creation. The scrollFactor of the graphic changes, but not the one of the label).

**Comment by AdamAtomic** [comment]
ok both the scrollfactor thing and the camera thing should be good to go now!
