### ISSUE TITLE
Path auto-rotate only works for diagonal sections

### ISSUE THREAD

**Issue by BillyWM** [AdamAtomic/flixel#154]
I noticed it doesn't always rotate the object along the path, namely straight sections. It looks really strange to have a sprite dragging its butt end along backwards :)

Anyway, it's a simple fix:

https://github.com/BillyWM/flixel/commit/f501b34c46e7b02b8c87394ba472c38e4e1f9141

**Comment by AdamAtomic** [comment]
nice!  just added that fix, should go out to the master branch tonight :)
