### ISSUE TITLE
FlxG.getPlugin(Class) iterating over elements

### ISSUE THREAD

**Issue by paulmoore** [AdamAtomic/flixel#156]
During the loop, the array index counter 'i' is being incremented twice, causing every other plugin to be missed (e.g. org.flixel.plugin.TimerManager).  To fix, remove the post increment 'i++' on line 980 of org.flixel.FlxG.

**Comment by BillyWM** [comment]
That's fixed in beta/dev
https://github.com/AdamAtomic/flixel/issues/144

**Comment by AdamAtomic** [comment]
yea, i'll push that fix over to master later today!  thanks :)
