### ISSUE TITLE
doFollow doesn't center the followed sprite properly

### ISSUE THREAD

**Issue by PaulGene** [AdamAtomic/flixel#16]
this seems to fix it for me:

_scrollTarget.x = (width>>1)-followTarget.x-(followTarget.width>>1)+(followTarget as FlxSprite).offset.x;
_scrollTarget.y = (height>>1)-followTarget.y-(followTarget.height>>1)+(followTarget as FlxSprite).offset.y;

**Comment by AdamAtomic** [comment]
I think I pasted this code in there already
