### ISSUE TITLE
Sounds mute after pause

### ISSUE THREAD

**Issue by noidexe** [AdamAtomic/flixel#160]
This affects the last commit AdamAtomic@d093bffe361d15b9b355

<h4>Steps to reproduce:</h4>

- In constructor:  <code>mySound = FlxG.loadSound(sound); </code>
- In update():  <code>if(/\* some key press or whatever */) mySound.play(); </code>
- Pause the game while mySound is playing then unpause it.

<h4>What should happen:</h4>

- mySound resumes and finishes playing(mySound.active becomes **false**).
- next time mySound.play() is called mySound plays.

<h4>What actually happens:</h4>

- mySound resumes and finishes playing(mySound.active gets stuck in **true**).
- next time mySound.play() is called mySound doesn't play(or at least no sound is heard).

**Comment by AdamAtomic** [comment]
i'm not able to reproduce this, but i'm also not sure how .active would get stuck on "true" or why that would prevent play from being called, very strange!

**Comment by noidexe** [comment]
I've created a new project and compiled it with a fresh download of flixel and still have the same issue. Here's the code:

``` as3
package
{

    import org.flixel.*;

    public class PlayState extends FlxState
    {
        [Embed(source = 'data/cartridge.mp3')] private var sndCart:Class;
        private var testSound:FlxSound;

        override public function create():void
        {

            testSound = FlxG.loadSound(sndCart);

        }

        override public function update():void
        {
            FlxG.keys.SPACE ? testSound.play(true) : testSound.play() ; // using play(true) makes it work again until the next pause/unpause
            super.update(); 
        }

    }
}

```

And the Project and binary download:
Project: https://github.com/noidexe/Soundtest
Binary: http://cloud.github.com/downloads/noidexe/Soundtest/Soundtest.swf

**Comment by noidexe** [comment]
This fixed it:

``` diff
 org/flixel/FlxSound.as |    5 +++++
 1 files changed, 5 insertions(+), 0 deletions(-)

diff --git a/org/flixel/FlxSound.as b/org/flixel/FlxSound.as
index 2c9b367..62525a3 100644
--- a/org/flixel/FlxSound.as
+++ b/org/flixel/FlxSound.as
@@ -358,6 +358,11 @@ package org.flixel
                    _channel = _sound.play(_position,0,_transform);
                    if(_channel == null)
                        exists = false;
+                   else
+                   {
+                       _channel.addEventListener(Event.SOUND_COMPLETE, stopped);
+                        
+                   }
                }
            }
            active = (_channel != null);
```
