### ISSUE TITLE
FlxG.collide does not work when objects go beyond FlxG.width

### ISSUE THREAD

**Issue by WEREMSOFT** [AdamAtomic/flixel#161]
Hi everyone.

I have a hero, an enemy and bullets.

lots of Bullets are in a FlxGroup
1(one) Enemy are in a FlxGroup

Enemy walks to the right constantly.

In the update method of the PlayState I have:

```
    public override function update():void
    {
        super.update();
        FlxG.collide(bullets, enemys, onCollidesBulletsEnemys);
        FlxG.log(soldier.x);
        FlxG.collide(soldier, enemys);  
    }
```

The soldier stop colliding with the enemies when both are beyond FlxG.width value. Same with bullets.

I try changing the size of the canvas and always the collision stop working as I said.

**Comment by AdamAtomic** [comment]
yea, by default FlxG.worldBounds is set to roughly the size of the screen - if you change the size of the worldBounds you should be ok!

**Comment by WEREMSOFT** [comment]
Works. Using this code on the constructor.

FlxG.worldBounds.width = _level.width;
FlxG.worldBounds.height = _level.height;
