### ISSUE TITLE
Mouse screenX/Y now incorrect

### ISSUE THREAD

**Issue by photonstorm** [AdamAtomic/flixel#162]
Based on v2.55 in dev branch, this:

screenX = (_point.x - camera.x)/camera.zoom;

breaks the result when the game has a zoom mode > 1.

For example:

Place mouse cursor at x 160. screenX will now report a value of 80. Everything is out by a factor equal to the game zoom level.

**Comment by AdamAtomic** [comment]
ah balls.  all these mouse bugs just from one little fix a few versions ago!!  i'm on it...

**Comment by AdamAtomic** [comment]
yea, idiot me had an unnecessary call in Mouse.updateCursor(), should be fixed now :)
