### ISSUE TITLE
Flixel Camera Incorrectly Setting Background

### ISSUE THREAD

**Issue by arkeus** [AdamAtomic/flixel#164]
In line 230 of FlxCamera.as color is being set as a 24 bit color:

_color = 0xffffff;

But I believe it should be 32 bits:

_color = 0xffffffff;

In FlxG when there is no camera it's returning it in this format (although in this case it's returning the opposite color).

```
        if(FlxG.camera == null)
            return 0xff000000;
        else
            return FlxG.camera.bgColor;
```

I believe this is the issue that is causing people to get trails on their sprites when they don't draw a background or manually set FlxG.bgColor, please see:

http://flixel.org/forums/index.php?topic=4165.0

Thanks.

**Comment by AdamAtomic** [comment]
iiinteresting - _color actually refers to the tint of the camera, not the clear color, but I just simplified some stuff with the camera fill behavior that seems to work fine without sprite trails here, i'll push it up soon!
