### ISSUE TITLE
Small issue for 10.3 and strict editors

### ISSUE THREAD

**Issue by WingEraser** [AdamAtomic/flixel#165]
Class: FlxPreloader

line 130
_init = false; --> this._init = false;

line 146
_init = true; --> this._init = true;

Reason: _init got occupied by playerglobal.swc Flash Player 10.3.
public dynamic class Object
{
    ...
    [API("675")]
    public static function _init():*;
    ...
}

Class: VCR
line 269
return FlxG.log("ERROR: Empty flixel gameplay record.");

Reason: it doesn't return anything. Use curly brackets:
{
    FlxG.log("ERROR: Empty flixel gameplay record.");
    return;
}

Class: FlxTilemap
line: 739, 745, 751, 757, 763, 769, 775, 781
Reason: Same here, it doesn't return anything. Use curly brackets:
{
    walkPath(Data,i,Points);
    return;  
}

**Comment by AdamAtomic** [comment]
awesome, i'm on it! i'll have these fixes pushed up shortly
