### ISSUE TITLE
Debugger buttons active even when not visible

### ISSUE THREAD

**Issue by photonstorm** [AdamAtomic/flixel#166]
Strange one.. the Debug buttons are active even if the Debugger isn't showing - you can still click the space where the buttons appear to toggle them on/off! May be a side effect of using forceDebugger = true, but definitely happens.

**Comment by noidexe** [comment]
I experienced it too in a debug compile without using forceDebugger = true

**Comment by AdamAtomic** [comment]
Hmmm... i'm just using mouse event listeners on the main thing, I would think that setting the whole debugger to !visible would work right!

**Comment by AdamAtomic** [comment]
oh i'm adding the click handlers to the stage!  ok i know a few different ways to correct this...

**Comment by AdamAtomic** [comment]
ok that should be fixed now!
