### ISSUE TITLE
FlxSound --> "_channel" can cause a null value exception in some cases

### ISSUE THREAD

**Issue by krix** [AdamAtomic/flixel#17]
if you try to play many many sounds at once (like 60 or so), it appears that the _channel variable can be null and cause a null value exception.

in FlxSound.as line 147 and 157 it's like this:

<pre style='height:50px'><code>if(_channel == null)
{
_channel = _sound.play(0, 0, _transform);
_channel.addEventListener(Event.SOUND_COMPLETE, stopped); //<-- _channel can be null here..
}</code></pre>

it works for me if i check for null values again..

<pre style='height:50px'><code>if(_channel == null)
{
_channel = _sound.play(0, 0, _transform);
if(_channel != null)  _channel.addEventListener(Event.SOUND_COMPLETE, stopped);
}</code></pre>

would be great if you can add this additional check to prevent this exception.
or i can try to figure out more about this error.

otherwise flixel rocks!! :)

**Comment by AdamAtomic** [comment]
Ok should be rolled in the next push (coming soon)
