### ISSUE TITLE
One-frame animations never finished

### ISSUE THREAD

**Issue by Markham** [AdamAtomic/flixel#18]
If you play an animation that has a frame-rate of zero, most commonly the case with one-frame animations, the FlxSprite's "finished" flag is never set to true.

**Comment by Markham** [comment]
There's also the whole dividing-by-zero issue in the FlxAnim class.  Line 19, where delay is set in the constructor function, can be fixed with this:

delay = (FrameRate>0)?1.0/FrameRate:0;

**Comment by AdamAtomic** [comment]
ok these should be cleaned up in the next push!
