### ISSUE TITLE
32x16 Image for FlxBlock

### ISSUE THREAD

**Issue by p-groarke** [AdamAtomic/flixel#20]
Hello, when using a 32x16 image for a 32x16 block, the visual output is random. Sometimes the block is twice the left 16x16 tile, sometimes the other half doubled, sometimes the good image... This is different per FlxBlock in the state. 

I'm not sure what more info I can say... this is a pretty basic moving platform, and the blocks are added to an array in my LevelState.

**Comment by AdamAtomic** [comment]
Yea FlxBlock only does squares right now I think?  You can get the same basic effect by creating a sprite instead of a flxblock and setting .fixed = true;

**Comment by p-groarke** [comment]
oh, ok. thanks. I guess I'll modify my graphics for now, hopefully we'll see this added some-day ;)

**Comment by AdamAtomic** [comment]
Using a sprite instead should work identically - they have the same collisions and everything, Block is really only useful for tiling stuff; that's the only added functionality.  They all inherit from core so you can even mix and match them in a collision check!

**Comment by p-groarke** [comment]
Sweet, I'll give it a try. thnx again!

**Comment by p-groarke** [comment]
I am trying to close this, lol

**Comment by AdamAtomic** [comment]
closed!
