### ISSUE TITLE
FlxText cant support non-English characters

### ISSUE THREAD

**Issue by nshen** [AdamAtomic/flixel#21]
FlxText cant support non-English characters ,it doesn't display

**Comment by Markham** [comment]
It's probably more that the embedded font doesn't support non-English characters.

**Comment by nshen** [comment]
could you fix that in a future version? although the embedded font is very beautiful,but not everyone speak english..

**Comment by Markham** [comment]
The font contains the characters for most Latin-character-based languages, and appears to be available through a free license.  I'm not sure if Adam can find one that contains more characters than that while being free to use, but that doesn't stop you from embedding your own font and using that.

**Comment by nshen** [comment]
sorry my english is not good, I mean a language not character, why it must embed font?
add(new FlxText(0,0,100,"I am Chinese ,中文无法显示?"))

**Comment by Markham** [comment]
The current font is embedded into FlxGame with this line:
[Embed(source="data/nokiafc22.ttf",fontFamily="system")] protected var junk:String;

You can use this line in your game's code to embed a font you want to use by changing the source variable to the font to use and the fontFamily variable to a name to use in the FlxText setFormat function.

**Comment by AdamAtomic** [comment]
Yea it sounds like this is just a font problem, it's hard to find a good bitmap font (which is important for flixel) that supports more than basic latin characters

**Comment by ryanhex53** [comment]
you can set the ”embeddedfont“ param in FlxText constructor to false, and set font = "_sans". if you need to display chinese chars.
