### ISSUE TITLE
FlxTilemap collision issues

### ISSUE THREAD

**Issue by cdp1001** [AdamAtomic/flixel#24]
I just noticed that if you try to collide a FlxCore with a FlxTilemap and the FlxCore is partially outside the tilemap there is a possible bug. If the FlxCore hits a solid tile inside the tilemap, the FlxCore will jump and get stuck inside the tilemap.

The way around this currently (v1.5) is to add a buffer zone of non-collideable tiles around the edges of a tilemap so your FlxCore is safetly inside before it can collide with any solid tiles.

**Comment by AdamAtomic** [comment]
this should all be fixed in v2.0 going up tonight or tomorrow!  re-open if i'm lying :)
