### ISSUE TITLE
[Flx 1.54] BUG - Tilemap-Sprites collision bug depending on parameter order

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#27]
I found a problem in the collision code:

Let's say...
lyrMain is a layer that contains ONE tilemap.
lyrPlayer is a layer that contains ONE player sprite.

[CODE] FlxG.collideArrays(lyrMain.children(), lyrPlayer.children()); [/CODE]

Works as expected, the the player collides just the collidable tiles inside the tilemap.

[CODE] FlxG.collideArrays(lyrPlayer.children(), lyrMain.children()); [/CODE]

This fails, the tilemap is collided as if it were just a core (one big rectangle), not working as expected.

This is pretty ill-defined, and regardless of any documentation that could explain it... it's hard to find and fix. I suggest that both work the same way to make it more intuitive on the library user.

Regards

**Comment by AdamAtomic** [comment]
i completely agree, and i will have this fixed by monday!  collisions are going to be...better :)

**Comment by ghost** [comment]
Hey, thanks for taking this issue (and the other one) into account Adam. Keep rockin' :)
