### ISSUE TITLE
[Flx 1.54] BUG - Weird collision behaviour when changing width/height of sprite

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#28]
I'm doing some tests on Whacky Whacky (for Flan export) and found out that, differently from the 1.25, the 1.54 weirds up heavily when changing width/height of an object.

Previous behaviour (1.25): http://www.tbam.com.ar/play--whacky-whacky.php
New behaviour (1.54): http://www.swfcabin.com/open/1264609275

What's going on?  
Hehehe

[CODE, The size adjusting snippet]
        protected function adjustPlayerSize():void
        {
            _player.offset.x=Math.floor(16_-(_player.scale.x - 1)/2);
            _player.offset.y=Math.floor(16_-(_player.scale.y - 1)/2);

```
        _player.width=16*(_player.scale.x);
        _player.height=16*(_player.scale.y);
    }
```

[/CODE]
[CODE, the growing snippet]
            _player.scale.x+=0.15;
            _player.scale.y+=0.05;
            adjustPlayerSize();
[/CODE]

Regards

**Comment by AdamAtomic** [comment]
i have no idea o_O  may have something to do with the 1.54 collision code?

**Comment by ghost** [comment]
Probably. I haven't checked deep into it... If you implemented the velocity-aware response as we talked someday perhaps it weirds up because it's taking into account a zero (or low) velocity as "coming from the left/right" (as if it were negative/positive) or something, boosting the push.

Those are usual responses depending on the collision order (horizontal-vertical or viceversa)... that's why I hate writing collision code XD

**Comment by amigarad** [comment]
Hi, has this been corrected in the latest update? I am having a similar problem (sprite disappearing offscreen) when giving variable values to the height and width of a sprite.

I tried updating to the latest flixel libraries but then found that the "hitFloor" function wasn't there anymore. Not sure if that was on me, though. I'll try again, but I am curious to see if this height/width problem is still occuring in the latest update...

**Comment by AdamAtomic** [comment]
in the new API hitFloor is hitBottom instead - not sure if that behavior is still there or not though!

**Comment by ghost** [comment]
I'm almost almost sure this doesn't happen anymore in Flx 2 :)
