### ISSUE TITLE
[1.56] BUG - Collision problems

### ISSUE THREAD

**Issue by fefranca** [AdamAtomic/flixel#29]
Adam, I couldn't quite catch this yet.. but 1.56 introduces some weird bugs while trying to override collision functions (hitWall / hitFloor / hitCeiling), most likely because it completely ignores those functions on your new code.

**Comment by AdamAtomic** [comment]
you are totally right, sorry about that!  i think i know how to fix that fairly easily...

**Comment by AdamAtomic** [comment]
well the algo is getting sort of absurd and special casey (my fault) but it should respect those functions in the "overlapping but not moving" case now

**Comment by fefranca** [comment]
Oh wow that was a fast bugfix Adam ;-) Works fine on my game now. Cheers!
