### ISSUE TITLE
Previous states still exist after changing states

### ISSUE THREAD

**Issue by Markham** [AdamAtomic/flixel#3]
When the state is changed, it seems that previous states aren't actually removed.  Buttons from a previous menu are still click-able, and when testing Mochi leader-boards, I found that the button function that calls the leader-board stuff and sends a score to it is called for every instance of the game state called up previously as well.  I was able to tell this by tracing the current game's score in the function called when the button is clicked - the current score would be traced, but so would the scores of every past game played.

**Comment by AdamAtomic** [comment]
I think to fix buttons and some other problems today I need to fix this en route, i'll keep you posted!

**Comment by AdamAtomic** [comment]
With any luck this should also be fixed in 1.34, let me know if it's still a problem!  Certain objects like Mochi things may need to be manually removed by overriding the state's destroy() function and specifically removing it...
