### ISSUE TITLE
Player sticks to y of moving platform

### ISSUE THREAD

**Issue by p-groarke** [AdamAtomic/flixel#30]
I pulled the latest Flixel today, and a weird and quite important bug arose. I have moving platforms, and if my player jumps under a platform going down, he sticks to the y and goes down with the platform. I also can't jump if the platform is going down...

There's lot's of code related, but the basics are that I can jump through the platform:

```
    override public function hitCeiling(Contact:FlxCore=null):Boolean
    {
        if(Contact is FallBlock || Contact is MovingBlock)
        {
            return false;
        }


        else
        {
            return super.hitCeiling();
        }
    }
```

I use a simple boolean trigger in the hitfloor function (method?) so my player can jump. In the player update function (method?), after super.update(); I use if(this.y !=0){jump=false); so basically the hitfloor trigger gets processed first and my player can jump if on a moving platform... Not sure if this is clear though.

I also use this in the hit floor so my character doesn't snap on platforms:

```
            if(last.y+(height-2) > Contact.y)
            {
                return false;
            }
```

Anyway. If you need more code just ask, or maybe the last commit wasn't 100% stable stuff? I reverted to 1.54.

**Comment by p-groarke** [comment]
Just read fefranca's issue and tested 1.57. This issue is somewhat resolved. But now, I can't jump when the platform is going UP!? lol, just say if you need more info.

**Comment by AdamAtomic** [comment]
thanks for reporting this!  i am working right now on a major revamp that will hopefully clear up some of the humpty-halfway collision weirdness (i am getting some doing sokoban shit too).

**Comment by AdamAtomic** [comment]
all fixed!  http://flixel.org/flxcollisions/
