### ISSUE TITLE
[1.57] tilemaps moved upward by 1 pixel

### ISSUE THREAD

**Issue by p-groarke** [AdamAtomic/flixel#31]
Hey, just to point this out. The title says it all, not really a bug but it's good to know. You might want to write it in the release notes though.

**Comment by p-groarke** [comment]
I' m actually thinking it's my player that was pushed down a pixel. Or anyhow he starts inside the tilemap now... and I'm unfortunately not making a digging game :P

**Comment by AdamAtomic** [comment]
hrrmm sounds like collision or offset problem possibly, lets see if the big collision update fixes it this weekend?  unfortunately it includes an API overhaul...

**Comment by AdamAtomic** [comment]
i still haven't seen anything like this, if it's still a problem when the update comes out feel free to re-open!
