### ISSUE TITLE
Cursor management of FlxG needs improvement

### ISSUE THREAD

**Issue by NeoTiger** [AdamAtomic/flixel#32]
The current implementation of FlxG.showCursor() and FlxG.hideCursor() is a bit awkward, because FlxG.showCursor(ImgCursor) can not be used to change the graphic of the cursor before removing the previous one with a call to FlxG.hideCursor().

Furthermore, FlxG.showCursor() can't be called in the constructor of FlxGame's instance to define a standard cursor, because the FlxGame instance won't have its _buffer set before the first onEnterFrame event is triggered by Flash.

Suggestions:
1. Add a method "setCursorGrapic()" to FlxG, which handles the setting of a cursor graphic independent from showCursor() - just have showCursor() call setCursorGraphic() when called with a parameter for backward compatibility.
2. Make showCursor() check whether a cursor is already active and whether _buffer actually exists.
3. Have a private property on FlxG that reflects the visibility state of the cursor
4. In FlxGame.onEnterFrame(), when it creates the _buffer, also "addChild" the cursor  if the property from (3) declares it as visible.

**Comment by AdamAtomic** [comment]
totally agreed, i will try and get this in soon!

**Comment by NeoTiger** [comment]
Here's the way I modified FlxG:

```
    /**
     * Set the mouse cursor to some graphic file.
     * Pass "null" or no parameter to use the system cursor.
     * 
     * @param   CursorGraphic   The embedded image you want to use for the cursor.
     */
    static public function setCursorGraphic(CursorGraphic:Class=null):void
    {
        if(CursorGraphic == null)
            _cursorGraphic = new ImgDefaultCursor as Bitmap;
        else
            _cursorGraphic = new CursorGraphic as Bitmap;
    }

    /**
     * Shows the mouse cursor
     * 
     * @param   CursorGraphic   The image you want to use for the cursor.
     */
    static public function showCursor(CursorGraphic:Class=null):void
    {
        if (CursorGraphic != null) 
        {
            setCursorGraphic(CursorGraphic);
            if (_game._cursor) hideCursor();
        }
        if (!_game._cursor) _game._cursor = _game._buffer.addChild(_cursorGraphic) as Bitmap;
    }

    /**
     * Hides the mouse cursor
     */
    static public function hideCursor():void
    {
        if(_game._cursor == null) return;
        _game._buffer.removeChild(_game._cursor);
        _game._cursor = null;
    }
```

**Comment by NeoTiger** [comment]
I also like to note at this opportunity that Flixel does not automatically hide and show the cursor if the real cursor leaves the stage. It leaves the SWF-cursor sitting idle at the border of the stage until the mouse reenters it. It would be great, if the framework could handle this too bit its own, so I don't have to hook into MouseEvents for this.

**Comment by AdamAtomic** [comment]
For 2.0 I made the cursor a FlxSprite, and a member of FlxG.mouse - it can be access directly or with some helper functions (show, hide, load, unload).  Also handles the out/over stuff!
