### ISSUE TITLE
overlaps() not working correctly with parallaxed vs. non-parallaxed sprite

### ISSUE THREAD

**Issue by NeoTiger** [AdamAtomic/flixel#33]
If sprite A has a "regular" scrollFactor of Point(1, 1) and sprite B has anything irregular like Point(1.5, 1.5), overlap detection does not work correctly, because FlxG.scroll values are ignored for A's position.

Current code is:

```
        var tx:Number = x;
        var ty:Number = y;
        if((scrollFactor.x != 1) || (scrollFactor.y != 1))
        {
            tx -= Math.floor(FlxG.scroll.x*(1-scrollFactor.x));
            ty -= Math.floor(FlxG.scroll.y*(1-scrollFactor.y));
        }
        var cx:Number = Core.x;
        var cy:Number = Core.y;
        if((Core.scrollFactor.x != 1) || (Core.scrollFactor.y != 1))
        {
            cx -= Math.floor(FlxG.scroll.x*(1-Core.scrollFactor.x));
            cy -= Math.floor(FlxG.scroll.y*(1-Core.scrollFactor.y));
        }
```

What really would make more sense is if it's just checked whether 

(scrollFactor.x != Core.scrollFactor.x || scrollFactor.y != Core.scrollFactor.y)

to do the scrolling-compensation.

**Comment by NeoTiger** [comment]
Sorry, was bogus. Just saw that it's a different approach with the same result.

**Comment by AdamAtomic** [comment]
np :)  i doublechecked the code too, it looks alright...i'm redoing collisions currently, and those WON'T take scrollfactor into account, it just gets too damn hairy
