### ISSUE TITLE
Key for developer console not working on German keyboard

### ISSUE THREAD

**Issue by NeoTiger** [AdamAtomic/flixel#34]
(event.keyCode == 192) only works on US keyboard layout. The keyCode for that key on a German keyboard layout is "220".

Since that number collides with another key on the US layout, the safest way to support both layouts would be to check the charCode too, which is different on the US layout:

```
if(event.keyCode == 192 || event.charCode == 220 && event.keyCode == 220)
```

First line in definition of FlxGame.onKeyUp()

**Comment by AdamAtomic** [comment]
noted!  i'll try and get it in the next release
