### ISSUE TITLE
Mouse cursor "twitching" during scrolling

### ISSUE THREAD

**Issue by NeoTiger** [AdamAtomic/flixel#35]
If the camera scrolls and a mouse cursor is displayed, it isn't static but "twitching" 1 pixel. Reason is in FlxGame.onEnterFrame():

```
            if(_cursor != null)
            {
                _cursor.x = FlxG.mouse.x + FlxG.scroll.x;
                _cursor.y = FlxG.mouse.y + FlxG.scroll.y;
            }
```

Since FlxG.scroll.\* is a float and not Math.floor()'ed, it can cause rounding errors. Problem was fixed when I put Math.floor() around those.

**Comment by AdamAtomic** [comment]
rad, noted!  i'll try and get this in the next build

**Comment by AdamAtomic** [comment]
done!  FlxG.mouse has new variables, screenX and screenY, that are perfect for this :)  should be public tonight!
