### ISSUE TITLE
FlxButton.onMouseUp(): redundant scroll-normalization

### ISSUE THREAD

**Issue by NeoTiger** [AdamAtomic/flixel#36]
I had a FlxButton on a UI Element which is on a layer set to scrollFactor = (0,0) and discovered that the button's click area was not where it was supposed to be when the camera was scrolled (i.e. FlxG.scroll != (0,0). Tracking the error, I discovered that in FlxButton.onMouseUp an overlapsPoint check was made with the mouse coordinates being normalized to a scrollFactor == (1,1) layer.

Problem is, overlapsPoint() does the same normalization again on the coordinates which are passed to it, so basically it does it twice, which is the cause for the problem. Altering

```
            if(_off.overlapsPoint(FlxG.mouse.x+(1-scrollFactor.x)*FlxG.scroll.x,FlxG.mouse.y+(1-scrollFactor.y)*FlxG.scroll.y)) _callback();
```

to 

```
            if (_off.overlapsPoint(FlxG.mouse.x, FlxG.mouse.y)) _callback();
```

made the button behave correctly.

**Comment by AdamAtomic** [comment]
fixed!  will go up soon :)  buttons have been revamped to extend the new FlxGroup class (formerly FlxLayer) so a lot of the button code has been made much more sane, and much less stupid :)  so has overlap actually!  good catch
