### ISSUE TITLE
FlxKeyboard.as:  Backspace maps to "DELETE", Delete key to nothing

### ISSUE THREAD

**Issue by NeoTiger** [AdamAtomic/flixel#37]
Suggested Fix:

Add line
        public var BACKSLASH:Boolean;
to properties of the class and within its constructor, replace
            addKey("DELETE",8);
by
            addKey("DELETE",46);
            addKey("BACKSPACE",8);

**Comment by AdamAtomic** [comment]
yea, i'm on a mac keyboard :P  i'm adding these changes right now, should be available shortly!  also i'm assuming you meant BACKSPACE in the first bit there?

**Comment by NeoTiger** [comment]
oops, my finger typing agent needs fixing :D
