### ISSUE TITLE
hitRight() calls hitLeft() - line 446 in FlxObject.as

### ISSUE THREAD

**Issue by knivel** [AdamAtomic/flixel#38]
The hitLeft() method works fine, but when I override hitRight() I get hitLeft() behavior as well. I checked in FlxObject.as and hitLeft() looks like this:

public function hitLeft(Contact:FlxObject,Velocity:Number):void
{
    if(!fixed)
        velocity.x = Velocity;
}

and hitRight() looks like this:

public function hitRight(Contact:FlxObject,Velocity:Number):void
{
    hitLeft(Contact,Velocity);
}

**Comment by AdamAtomic** [comment]
yes i wrote that code :)  what is the problem?  are you calling super.hitRight?

**Comment by knivel** [comment]
Well, I was overriding both hitRight and hitLeft in my Player class for some wall-jumping code. I called super.hitRight and super.hitLeft in my respective override functions, but since hitRight calls hitLeft, when my Player hit a wall on the right, both my hitRight and hitLeft custom code fired.

I ended up just copying the contents of hitLeft in FlxObject into hitRight as well, and now my override code gets called independently. I guess I don't get how you're supposed to override hitLeft and hitRight separately as they are now.

**Comment by AdamAtomic** [comment]
You can override them separately, that's the whole point!  It's just if you call super.hitRight from your hitRight override, THAT will call super.hitLeft.

**Comment by knivel** [comment]
Ohh, I gotcha. Thanks!

**Comment by AdamAtomic** [comment]
no prob!  it's weird, but it means you don't have to write wall-bounce code twice, which is nice for a lot of stuff :)
