### ISSUE TITLE
Moving FlxGroup objects don't collide properly.

### ISSUE THREAD

**Issue by Markham** [AdamAtomic/flixel#39]
I've got a player made of multiple sprites in a FlxGroup.  The FlxGroup has a y acceleration, and causes severe lag (around 7 FPS) as it falls downward over the FlxSprite it is supposed to collide with.  Overlap works just fine, as I have a FlxTileblock that kills the player when it moves off screen. When that happens the framerate jumps to 60.

**Comment by AdamAtomic** [comment]
Crap, you're exactly right.  The group members' collision data won't update, since the group just changes their positions, not their velocities/accelerations/etc.  And groups don't add themselves to the quadtrees...hrmm.  Maybe groups should add themselves, just be flagged as !solid by default?  It won't fix this but it would at least give you ONE object in the group (the group itself) with legit collision information

**Comment by AdamAtomic** [comment]
Ok I think I know a way around this, I might not get it put together til monday or tuesday though

**Comment by AdamAtomic** [comment]
Ok i just pushed some stuff up that MAY help, let me know if it makes it any worse :P

**Comment by Markham** [comment]
The FlxGroup collides now. :)  Framerate didn't improve, though, so I still have to figure out what I did that is messing with the collision scripts.

**Comment by Markham** [comment]
I thought it was working, but I only had the character being created level with the platform.  I set the character to be created 50 pixels above the platform, and it didn't move when the group's solid was set to true.  I traced the group's y variable and found that the group moves and collides, but the contained sprites don't seem to be moved with it.

**Comment by AdamAtomic** [comment]
thaaaat would be because i left out a fairly important bit of code in the collision resolution stuff, try out v2.13, lemme know if it helps/hurts (if you get the chance/inclination)

**Comment by Markham** [comment]
The group members still float around above the platform at their original starting point.

**Comment by AdamAtomic** [comment]
Ok I fiddled with it some more, if you're bored and want to see if v2.15 helps/hurts that'd be cool :)

**Comment by mhughson** [comment]
I am still seeing (what I think is) the same issue.  I'm not sure what version of flixel I am on, but I'm 99.9% sure I got it after Feb 15th.  It is labeled: AdamAtomic-flixel-b9fe564.

EDIT: I am using flixel v2.35 [debug] according the the output panel.

Everything worked fine when I was manually adding the objects to my gameplay state, but as soon as I converting things to FlxGroups, moving platforms stopped colliding with the player.

**Comment by AdamAtomic** [comment]
yea this was a horrible idea from the outset, flxgroups can no longer move in v2.50
