### ISSUE TITLE
x and y of FlxButton of no use in update()

### ISSUE THREAD

**Issue by Hajus** [AdamAtomic/flixel#40]
I can position the button in create() of the FlxState. I can move it around in update() via velocity and acceleration.

I can not reposition it in update() by setting x and y anew. While a trace() shows that the variable is set, it does not change the position of button on the state.

I helped myself by "button.reset(newX,button.y);", but this is only valid as long the y variable is in sync with the actual position.

**Comment by AdamAtomic** [comment]
groups need to use reset currently, to keep all their members up to date

**Comment by AdamAtomic** [comment]
moving this to the closed issue list...
