### ISSUE TITLE
FlxU.setWorldBounds

### ISSUE THREAD

**Issue by Markham** [AdamAtomic/flixel#41]
I'm experiencing a couple issues with setWorldBounds.  When I let FlxG.followBounds run it with settings that probably don't completely contain all objects being collided with, collisions work but with severe lag.  If I execute the function in a way that contains all the objects being collided, there is no slowdown, but nothing collides.

**Comment by AdamAtomic** [comment]
so followBounds uses a left, top, right, bottom format, while worldBounds uses left, top, width, height format - would that account for the difference in behavior?  (when followbounds calls worldbounds it does the conversion on its own)

**Comment by Markham** [comment]
I'm not sure what the difference is.  If the left is 0, and the right is 20000, is the width not the right side?  I've been looking through the code - what if someone sets the followBounds to a negative left or top?

Changing the default variables of FlxU.setWorldBounds to this also replicates the non-colliding problem:
    X = -64_FlxG.width;
    Y = -64_FlxG.height;
    Width = 64_FlxG.width;
    Height = 64_FlxG.height;

**Comment by AdamAtomic** [comment]
that makes the bottom right corner of the world bounds at 0,0

**Comment by AdamAtomic** [comment]
moving this to the closed list for now...
