### ISSUE TITLE
Need an isPlaying property for FlxSound, or make play()/pause()/stop() virtual

### ISSUE THREAD

**Issue by michaelbartnett** [AdamAtomic/flixel#42]
I'm writing a tool for creating adaptive music running on top of Flixel with FlxSound, and it requires a way to tell if a sound is currently playing or not. Could we to add an isPlaying property to FlxSound, or make the play(), pause(), and stop() functions public so that it's possible add this functionality in ourselves?

I'm already maintaining my own copy of Flixel, edited to make the functions virtual, but I get the feeling I'm not the only one who would make use of this.

Thanks for an awesome framework!

**Comment by AdamAtomic** [comment]
You should be able to check FlxSound.active to see if the sound is playing

**Comment by michaelbartnett** [comment]
I initially tested out FlxSound.active after guessing that FlxSound.dead and FlxSound.visible don't do anything. I watered down my class to test this out and made a simple FlxGame and FlxState in which to instantiate, play, and stop a sound with a large interval of time between play and stop, calling update() every loop. Unfortunately the trace statement doesn't appear in the console window when I debug.

```
package
{
    import org.flixel.FlxSound;

    public class DeceptiveSound extends FlxSound
    {   
        override public function update():void
        {
            super.update();

            if (this.active == false) {
                trace("A sound went inactive!");
            }
        }
    }
}
```

**Comment by AdamAtomic** [comment]
update doesn't even get called if active is set to false :P  try tracing or FlxG.log()ing (which dumps to trace anyways) outside fo the sound class instead!

**Comment by michaelbartnett** [comment]
I'm sorry, I was kinda unclear and the rest of the code's too big & messy to post, but I am indeed calling FlxSound.update() within my own asset management classes each loop, if I add a trace() outside of the if() statement I get blasted with output, so it's definitely getting updated.

**Comment by AdamAtomic** [comment]
ah ok - yea I just checked the source and pausing a sound does NOT flag it as !active, so either I need to change that and make sure it doesn't break some of the other checks against activity, or I need to add a new variable.  Thanks for explaining!

**Comment by AdamAtomic** [comment]
This went up in 2.23!  Forgot to mark it here :)
