### ISSUE TITLE
FlxTileblock throws a runtime error if you pass it a non-zero Empties value

### ISSUE THREAD

**Issue by knivel** [AdamAtomic/flixel#44]
I fixed the problem in renderBlock() in FlxTileblock.as, line 98:

if(_rect != null) FlxG.buffer.copyPixels(_pixels,_flashRect,_flashPoint,null,null,true);

should be

if(_flashRect != null) FlxG.buffer.copyPixels(_pixels,_flashRect,_flashPoint,null,null,true);

_flashRect is defined the line before, and I can't find _rect defined anywhere.

**Comment by knivel** [comment]
rect and flashRect should have underscores in front of them.

**Comment by AdamAtomic** [comment]
good catch!  all fixed, get v2.16 :)
