### ISSUE TITLE
Minor Bug?: FlxEmitter's at function with FlxGroup (origin not instantiated)

### ISSUE THREAD

**Issue by YoriKv** [AdamAtomic/flixel#45]
FlxGroup is a FlxObject
FlxObject.origin is instantiated in FlxSprite, but not FlxGroup

Hence, the FlxEmitter's at function on a FlxGroup causes a null object exception

**Comment by AdamAtomic** [comment]
quite right!  quite right, i'm on it

**Comment by AdamAtomic** [comment]
ok all fixed, sorry about that!
