### ISSUE TITLE
Support panel button graphics do not show

### ISSUE THREAD

**Issue by Haledire** [AdamAtomic/flixel#48]
I've tried running the setup function from the game level and the state level.

Running setup from state level, I will momentarily see the graphic for Donate and close (they might all be landing at the same location), but the second show runs to place the panel properly, the button vanishes, and the only thing visible on the panel is the caption on the far right side

Despite this, the buttons still function - their hot spots still activate in what seems to be the proper locations, but they show no graphics.

There's no working sample available, so it's unclear at the moment if there is another step between setup and show that is missing.

**Comment by AdamAtomic** [comment]
try calling setup during flxgame and show during flxstate

**Comment by Haledire** [comment]
Doesn't change anything.  It seems because all of the buttons are FlxGroups and reset needs to be called (as per http://github.com/AdamAtomic/flixel/issues/closed#issue/40 ) to update group members (IE: the FlxSprite graphics) the only part of the button that gets updated is the hit area.

**Comment by AdamAtomic** [comment]
Ok I think this is working correctly now!  Will go out in the next update :)
