### ISSUE TITLE
FlxTilemap incorrectly handles collision at extremes

### ISSUE THREAD

**Issue by GregoryAveryWeir** [AdamAtomic/flixel#49]
I ran into this issue in 1.47, but from the source it appears to still be there. FlxTilemap.preCollide defines ix and iy as uints instead of ints.  Because of this, if the colliding object's x or y is less than the tilemap's x or y, the uint overflows and collision works wrong.  I'm guessing this doesn't come up much because few people use tilemaps that can be collided with from outside the tilemaps' bounds.  Changing ix and iy to ints appears to fix the collision mistakes.

**Comment by AdamAtomic** [comment]
Cool, all set!  Will ship out with v2.23 later today
