### ISSUE TITLE
Need Documenation

### ISSUE THREAD

**Issue by gigaclon** [AdamAtomic/flixel#5]
There should be a nanodoc.html in the root of the repository. This is needed for API changes

**Comment by AdamAtomic** [comment]
YES totally agree.  This is not a problem, might just take a week or two to get the cleaned up code from ivans.  The current build should have up to date in-code documentation, just a matter of getting the latest nanodoc installed locally so I can build a new HTML for you guys!

**Comment by gigaclon** [comment]
also is there a change we could get the javascript pop outs that describe the item we clicked on to appear to the right of the item instead of the top of the screen requiring me to scroll all the way up?

**Comment by AdamAtomic** [comment]
nanodoc has been like totally reskinned since then, it's much more functional now :) just a matter of getting my hands on it at this point :)

**Comment by echeese** [comment]
Why aren't you using standard asdoc style comments? It'd be much easier to use and my IDE has support for them (which would make it much easier for me as well)

**Comment by AdamAtomic** [comment]
I don't even know what asdoc is, or what IDEs support that, but I just sent a reminder to ivans to try and get my hands on nanodoc so we can at least have some reference for all the crazy new stuff, should be another week or two tops, sorry about the delays!

**Comment by echeese** [comment]
asdoc is by adobe and comes with Flex SDK. I know for sure FlashDevelop supports it: http://imgur.com/kUBSU.png and I'd be more than happy to change the codebase over for you

Edit: The top image is what currently happens, the 2nd is after I switched comment styles

**Comment by AdamAtomic** [comment]
INTERESTING very interesting, I will definitely think it over, it'd be rad to have it always integrated like that!

**Comment by p-groarke** [comment]
Wow, that would be quite nice. +1 for asdoc :D

**Comment by stupergenius** [comment]
I was surprised to see nanodoc being used in favor of asdoc as well. It is well supported in Flex Builder.

**Comment by AdamAtomic** [comment]
Ok ASDoc has been rolled in to the source files and docs output is included in the source here on the github.  Also will try and keep the latest stuff hosted here:

http://flixel.org/docs/
