### ISSUE TITLE
FlxText won't wrap text the first time

### ISSUE THREAD

**Issue by JoeOsborn** [AdamAtomic/flixel#50]
In order to get text wrapping correctly in an FlxText, I've had to do the following dance:

var string : String = "a really long string that will certainly wrap, I betcha";
var fltext : FlxText = new FlxText(0, 0, 50, string);
fltext.text = string;

Otherwise, it won't wrap.

On a hunch, I tried repeating the "_regen = true; calcFrame()" invocation at the end of FlxText's constructor, and that also fixes the problem (i.e., it lets me pass in the text just one time to the constructor).  Using a null string and setting the text afterwards also fails; it seems like calcFrame() needs to get called twice to do its job.

**Comment by AdamAtomic** [comment]
man this was a weird one.  When FlxText was reading in the number of lines, it was getting CRAZY high numbers occasionally, I'm still not sure exactly why.  It's fixed now though!  Will ship it with v2.23 later today
