### ISSUE TITLE
Volume control -/+/0 doesn't work with the numpad in a windows keyb [+SOLUTION]

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#52]
inside the onKeyUp() @ FlxGame.as, here's the fix:

(At least in windows keyboards the keycodes for -/+/0 differ from regular to numpad)

<pre>
                switch(c)
                {
                    case 48:
                    case 96:
                        FlxG.mute = !FlxG.mute;
                        showSoundTray();
                        return;
                    case 109:
                    case 189:
                        FlxG.mute = false;
                        FlxG.volume = FlxG.volume - 0.1;
                        showSoundTray();
                        return;
                    case 107:
                    case 187:
                        FlxG.mute = false;
                        FlxG.volume = FlxG.volume + 0.1;
                        showSoundTray();
                        return;
                    case 80:
                        FlxG.pause = !FlxG.pause;
                    default: break;
                }
</pre>

**Comment by AdamAtomic** [comment]
this will be in 2.23, which should be up in an hour or two!

**Comment by ghost** [comment]
Cool :)
