### ISSUE TITLE
Add slopes to FlixelTilemap [feature request]]

### ISSUE THREAD

**Issue by vforsh** [AdamAtomic/flixel#53]
In this thread http://flixel.org/forums/index.php?topic=943.0 fefranca present FlxTilemapSloped class. But it is for Flixel 1.55. Please add this for new release of flixel.

**Comment by AdamAtomic** [comment]
that is awesome!  but incorporating this is not going to happen on the main branch any time soon - i'll hang onto this request but in the closed list!
