### ISSUE TITLE
FlxTilemap collision doesn't work on leftmost column

### ISSUE THREAD

**Issue by radix** [AdamAtomic/flixel#57]
I'm using current git as of twenty minutes ago, and I've got a FlxTilemap-based game. If my map has collideable tiles in the first column, they're not actually causing collisions. If I put in a buffer of tiles on the left before the column of collideable tiles, they start colliding. I'll attach two maps as an example.

**Comment by radix** [comment]
Ok, I can't see how to attach files, so I'll just paste in the maps and hope they don't get horribly formatted...

This one allows you to walk off the world to the left:

```
 2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4
 1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3
```

The following one doesn't:

```
 0,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4
 0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
 0,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3
```

**Comment by radix** [comment]
Ok, so actually I was running into even more collision problems than just tilemaps, and collision in my game was being generally extremely wonky... and I eventually tracked it down to these lines:

```
        var fx:* = tilemap.width/2 - FlxG.width/2;
        var fy:* = tilemap.height/2 - FlxG.height/2;
        FlxG.followBounds(fx,fy,fx,fy);
```

which I was running in my scene's create method. I don't even remember where they came from; I guess I cargo-culted them from some old example, but when I leave them in collision is extremely bizarre, and when I take them out everything works perfectly.

**Comment by AdamAtomic** [comment]
Ok this should be fixed (finally!) in the update that goes out later today - i optimized it a bit too but i haven't seen any framerate boost from that yet
