### ISSUE TITLE
FlxG.follow documents followTarget as an FlxObject, but it actually needs to be a FlxSprite

### ISSUE THREAD

**Issue by radix** [AdamAtomic/flixel#58]
If you pass a non-FlxSprite to FlxG.follow, it blows up because it tries getting FlxSprite-specific attributes off of it.

I ran into this while trying to do a FlxG.follow(tilemap), in an attempt to get my tilemap centered on the screen.

**Comment by AdamAtomic** [comment]
YES this happened to me too, will try and get this fixed soon!

**Comment by AdamAtomic** [comment]
Ok got rid of the sprite-dependent stuff, it wasn't doing much anyways - fix will go up on master and dev later today!
