### ISSUE TITLE
Empty FlxText shows white line.

### ISSUE THREAD

**Issue by GregoryAveryWeir** [AdamAtomic/flixel#59]
If I pass in "" as the initial text for a FlxText in the constructor, it shows a one-pixel-high white line at the requested width of the text box.  If I pass in " ", it behaves as expected: the text box is not visible.  This is the way it should behave for the null string, as well.

**Comment by AdamAtomic** [comment]
yes, totally agree, will fix that :)  thanks!

**Comment by AdamAtomic** [comment]
ok that actually only happens if you never call update on the textbox, which is why I never noticed it before...I'll make sure you can just call render on it safely though!

**Comment by AdamAtomic** [comment]
haha, i left out a zero _smacks forehead_...fix will go out in the next update to both dev and master branches later today!
