### ISSUE TITLE
[1.31] Collision not working in certain cases.

### ISSUE THREAD

**Issue by Markham** [AdamAtomic/flixel#6]
In my current game, I've been using the line
FlxG.collideArrays(_enemies,_blocks);
for collision, which in the latest version of collision code, doesn't seem to work. (The enemy sprites fall through the floor)

FlxG.collideArrays(_blocks,_enemies);
does work, but the previous code ran much faster as "dead" enemies won't iterate through every block since the code already skips over inactive objects, but with this line every block iterates through every enemy to see if it is active or not.

**Comment by AdamAtomic** [comment]
That's odd, the first version should work still :(  I wonder if it has to do with the logic comparisons?  Maybe I need some >= instead of just some >, I'll try some stuff out :)

**Comment by AdamAtomic** [comment]
replicated!  working on a solution...

**Comment by AdamAtomic** [comment]
ok there is a 1.32 available where that collision setup should work fine!  good catch!

**Comment by AdamAtomic** [comment]
closing report for now....

**Comment by Markham** [comment]
It doesn't seem to have changed anything.  Enemies and particles are still falling through floors and walls.

**Comment by AdamAtomic** [comment]
Yea github has not updated with any of my last 3 or 4 pushes, trying to figure out what's up!

**Comment by AdamAtomic** [comment]
Ok it looks like maybe they went through this time, checking the source now...yeah, try it now.  Not sure what happened there!
