### ISSUE TITLE
You can add a FlxObject to the same FlxGroup more than once...

### ISSUE THREAD

**Issue by edmundito** [AdamAtomic/flixel#60]
Not sure if this is the intended behavior, but I was able to unintentionally add a sprite to a group twice leading to unexpected results. Perhaps it should at least give me a warning on the console or something, or throw an exception. Unless there's a good reason why to add a sprite twice to the group...?

So, my workaround was to check first:

```
if (group.members.indexOf(sprite) < 0)
    group.add(sprite);
```

**Comment by AdamAtomic** [comment]
oh man i hadn't even considered that, very good point :)

**Comment by AdamAtomic** [comment]
ok i totally forgot to add this on the last billion updates, but its in 2.43!  thanks
