### ISSUE TITLE
FlxGroup::saveOldPosition corrupts _last value before it checked by others (like reset() and updateMembers()

### ISSUE THREAD

**Issue by sburavtsov** [AdamAtomic/flixel#62]
Notice that saveOldPosition called every update, and inside of it there is _last.x = x; _last.y = y;
Function updateMembers tries to check if x and y was changed by comparing them with _last, but saveOldPosition always makes them equal.

I've fixed it by:

```
    protected function saveOldPosition():void
    {
        if(_first)
        {
            _first = false;
            _last.x = 0;
            _last.y = 0;
            return;
        }
        //_last.x = x;
        //_last.y = y;
    }
```

and 

override public function reset(X:Number,Y:Number):void
        {
            saveOldPosition();
            super.reset(X,Y);
            var mx:Number;
            var my:Number;
            var moved:Boolean = false;
            if((x != _last.x) || (y != _last.y))
            {
                moved = true;
                mx = x - _last.x;
                my = y - _last.y;
                _last.x = x;
                _last.y = y;
            }

and

protected function updateMembers():void
        {
            var mx:Number;
            var my:Number;
            var moved:Boolean = false;
            if((x != _last.x) || (y != _last.y))
            {
                moved = true;
                mx = x - _last.x;
                my = y - _last.y;
                _last.x = x;
                _last.y = y;
            }

Not sure if it is good solution, waitng for you, Adam.

**Comment by AdamAtomic** [comment]
This whole system was deprecated in newer versions, so those corruptions shouldn't be a problem anymore :)

**Comment by AdamAtomic** [comment]
OK I lied I thoguth this was referencing something else, I am re-opening this and will check it out!  Thanks for your patience :)

**Comment by AdamAtomic** [comment]
ok this stuff was for-reals deprecated finally, no more horror of that particular flavor in v2.50-forward :)
