### ISSUE TITLE
Using an embed font for FlxText should be optional.

### ISSUE THREAD

**Issue by hima** [AdamAtomic/flixel#63]
Using an embed font can cause a problem to foreign languages, making them display the text incorrectly.  The choice to use an embed font or font from the system should be optional, maybe something like this

FlxText( args1, args2, ..., isEmbed = true ) 

With this, the default will be using an embed font.

**Comment by AdamAtomic** [comment]
ok I put this in, should go out with today's update to the dev and beta branches!
