### ISSUE TITLE
Uninitialized FlxG.elapsed in doFollow() 

### ISSUE THREAD

**Issue by zxzxlch** [AdamAtomic/flixel#64]
-- FlxG:681
scroll.x += (_scrollTarget.x-scroll.x)_followLerp_FlxG.elapsed;
scroll.y += (_scrollTarget.y-scroll.y)_followLerp_FlxG.elapsed;

Calling follow() from a FlxState class doesn't produce any effect. FlxG.elapsed returns returns NaN and so scroll.x and scroll.y are assigned NaN, which is why follow() failed to work.

Flixel v2.34

**Comment by AdamAtomic** [comment]
in tonight's release of dev and beta branches, FlxG.elpased should be properly initialized
