### ISSUE TITLE
Player gets stuck in between to stack FlxSprites

### ISSUE THREAD

**Issue by hamedn** [AdamAtomic/flixel#65]
Hey,

I have a class called FlxBarrier extending FlxSprite. In my game, I have 2 of these stacked on top of eachother. They both have the same height, width, and .x. So they form together to make a wall. Their bounding boxes are also perfectly connected. Whenever my player comes down while pushing against these 2 FlxBarriers, he gets stuck at the top of the bottom one. Despite the fact that they are perfectly aligned.

Here are some screenshots, excuse my crappy MSPaint skills: http://i40.tinypic.com/ezmpo4.jpg

**Comment by AdamAtomic** [comment]
you may need to set them as "fixed" to get the right collision behavior?  not sure...

**Comment by hamedn** [comment]
I already did this
