### ISSUE TITLE
Incorrect colouring when reloading graphic [With solution]

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#70]
suppose I do

<pre>
spr_.loadGraphic(Image);
spr_.color = 0xff0000;
</pre>

The sprite will be shown red.

But if after I execute that exact same lines again

<pre>
spr_.loadGraphic(Image);
spr_.color = 0xff0000;
</pre>

As color is kept the same, the color setter never reaches the calcFrame function, and the graphic doesn't have any colouring.

<pre>
        public function set color(Color:uint):void
        {
            Color &= 0x00ffffff;
            if(_color == Color) return;
</pre>

A fix could be to reset color to 0x00ffffff after a loadGraphic or createGraphic or whatever.

Regards
-Martín

**Comment by ghost** [comment]
Well, resetting to white wouldn't be as cool as just doing a calcFrame() after loadGraphic to apply the colouring and whatnot.

<pre>
        public function loadGraphic(Graphic:Class,Animated:Boolean=false,Reverse:Boolean=false,Width:uint=0,Height:uint=0,Unique:Boolean=false):FlxSprite
        {

                           //...

            height = frameHeight = Height;
            resetHelpers();
            calcFrame();          //<<<<<<<<
            return this;
        }
</pre>

**Comment by AdamAtomic** [comment]
Ok I dropped in a call to:

if(_ct != null) _framePixels.colorTransform(_flashRect,_ct);

In resetHelpers(), that should help properly initialize graphics with existing color AND alpha settings - let me know if it's still broke after the next beta goes out!
