### ISSUE TITLE
Adding a push state to FlxButton

### ISSUE THREAD

**Issue by brandoncash** [AdamAtomic/flixel#71]
As it stands, FlxButton only has normal and hover states.  It seems to me that having a push state would also be useful to many.  I have written a patched version of FlxButton and put the code at http://flixel.org/forums/index.php?topic=1589.0

This proposed version has a couple key changes:
Removed _pressed, since it was boolean
Added _state, which currently has 0 as normal, 1 as hover, and 2 as pushed.  If future states are needed, they could easily be added on
Removed the visibility() function, as it was boolean as well
Added a third parameter to loadGraphic(); you can still pass null as the second parameter if you don't have a hover state
Made the toggled on buttons show the pushed state

**Comment by bobthecoolscholar** [comment]
Awesome fix, thanks!

**Comment by AdamAtomic** [comment]
buttons are less crappy now and should address all this stuff :)
