### ISSUE TITLE
FlxSprite's loadGraphic/resetHelpers doesn't respect alpha

### ISSUE THREAD

**Issue by GregoryAveryWeir** [AdamAtomic/flixel#74]
I've got a game where a FlxSprite is changing its graphic while at alpha 0, then is fading in.  I was seeing a weird flicker, where it would be at alpha 1 for a frame when it loaded the new graphic.

From what I can tell, when FlxSprite loadGraphic calls resetHelpers, resetHelpers generates the new _framePixels but doesn't apply the appropriate color transform to it.  I'm using a workaround of calling calcFrame after loadGraphic, and it seems to resolve the issue.

It looks like the solution is to add the following line near the end of resetHelpers:
if(_ct != null) _framePixels.colorTransform(_flashRect,_ct);

**Comment by GregoryAveryWeir** [comment]
The bug is occurring in 2.23.

**Comment by AdamAtomic** [comment]
this should be fixed as of recently, someone was having similar troubles with colors not migrating over properly as well, thanks!
