### ISSUE TITLE
FlxButtons can be pushed even when the game is paused

### ISSUE THREAD

**Issue by brandoncash** [AdamAtomic/flixel#76]
Since the pushing of a FlxButton happens outside of the normal flixel update loop, it is possible to trigger the button's callback even when FlxG.pause is true.

This can easily be worked around by updating onMouseUp() to check if the game is paused:
protected function onMouseUp(event:MouseEvent):void
{
    if(!exists || !visible || !active || !FlxG.mouse.justReleased() || FlxG.pause || (_callback == null)) return;
    if(overlapsPoint(FlxG.mouse.x,FlxG.mouse.y)) _callback();
}

**Comment by AdamAtomic** [comment]
rad, added :)  thanks!
