### ISSUE TITLE
FlxG.follow() not working when called from create()

### ISSUE THREAD

**Issue by BTMPL** [AdamAtomic/flixel#77]
The cammera follow mode dosn't work when called from create() but does when called in update() (just once is ok). 

FlxG::doFollow() is to blame, the lines:

```
scroll.x += (_scrollTarget.x - scroll.x) * followLerp * FlxG.elapsed;
scroll.y += (_scrollTarget.y - scroll.y) * followLerp * FlxG.elapsed;
```

When called from FlxG::follow() witch is in turn called in your PlayState::create() sets the scroll.x / scroll.y to NaN because FlxG.elapsed is not yet set and is NaN

Adding a if-conditional like:

```
if(!isNaN(FlxG.elapsed)) {
    scroll.x += (_scrollTarget.x - scroll.x) * followLerp * FlxG.elapsed;
    scroll.y += (_scrollTarget.y - scroll.y) * followLerp * FlxG.elapsed;
}
```

Fixes it.

**Comment by BTMPL** [comment]
Other way of taking care of this bug is to change FlxG.as:49 from:

```
static public var elapsed:Number;
```

to

```
static public var elapsed:Number = 0;
```

Might be SDK issue (I'm using the newest Flex SDK 4) - the var is uninitialized thus NaN.

**Comment by brandoncash** [comment]
The second fix seems the best to me, but in setGameData(), FlxG.elapsed is set to 0.  This should be called from FlxGame's constructor, so I'm not sure why it's uninitialized.

**Comment by BTMPL** [comment]
It's not set to 0, it's set to null:

http://github.com/AdamAtomic/flixel/blob/master/org/flixel/FlxG.as#L643

**Comment by joshtynjala** [comment]
Noticed this too. Makes things hard for a newbie like me. A better fix might be to set FlxG.elapsed = Game._elapsed in FlxG.setGameData(), or to maybe set FlxG.elapsed = 0 in the FlxGame constructor after _elapsed is set to 0.

**Comment by brandoncash** [comment]
@BTMPL: looks like you're checking off master.  I'd recommend checking off dev, since it has a few updates.
That being said, scroll is still set to null there, but FlxG.elapsed is set to 0.

**Comment by BTMPL** [comment]
Ineed, looks like it's fixed in the dev branch.

**Comment by BTMPL** [comment]
Closing.
