### ISSUE TITLE
FlxTilemap collision does not work, when x is greater zero.

### ISSUE THREAD

**Issue by Chromanoid** [AdamAtomic/flixel#78]
FlxTilemap collision does not work, when x is greater zero. During update or sth. like that the collhull.x value is set to the x position of the tilemap (should be zero because colOffsets is used). a possible fix/workaround is to set collhull.x to zero in the preCollide-function of FlxTilemap.

**Comment by AdamAtomic** [comment]
ok dropped in a fix for that, should go out in the next public update!  I just added these lines to the top of preCollide():

//Collision fix, in case updateMotion() is called
            colHullX.x = 0;
            colHullX.y = 0;
            colHullY.x = 0;
            colHullY.y = 0;
