### ISSUE TITLE
FlxSprite bounding boxes are sometimes drawn incorrectly

### ISSUE THREAD

**Issue by brandoncash** [AdamAtomic/flixel#79]
It appears that some configurations of offset and width will make the bounding box render incorrectly.  In this proposed fix, I change it so that the rectangles are drawn at 0,0 and then blitted at the offset coordinates, rather than the other way around.

In FlxSprite.as, change drawBounds() to:
protected function drawBounds():void
        {
            _boundsVisible = true;
            if((_bbb == null) || (_bbb.width != width) || (_bbb.height != height))
                _bbb = new BitmapData(width,height);
            var bbbc:uint = getBoundingColor();
            _bbb.fillRect(_flashRect,0);
            var ofrw:uint = _flashRect.width;
            var ofrh:uint = _flashRect.height;
            _flashRect.width = width;
            _flashRect.height = height;
            _flashRect.x = 0;
            _flashRect.y = 0;
            _bbb.fillRect(_flashRect, bbbc);
            _flashRect.width -= 2;
            _flashRect.height -= 2;
            _flashRect.x++;
            _flashRect.y++;
            _bbb.fillRect(_flashRect,0);
            _flashRect.width = ofrw;
            _flashRect.height = ofrh;
            _flashRect.x = _flashRect.y = 0;
            _framePixels.copyPixels(_bbb,_flashRect,new Point(int(offset.x), int(offset.y)),null,null,true);
        }

**Comment by AdamAtomic** [comment]
haha, i spotted this one too, already added to my local copy!  fix will go out later tonight, thanks :)
