### ISSUE TITLE
[1.43]  Problems with scrolling buttons

### ISSUE THREAD

**Issue by Pishtaco** [AdamAtomic/flixel#8]
I've set a button's scroll factor to 0 (using the synch-scroll-with-layer thing). But the button still scrolls around the screen, and highlights when you put the mouse over it. However nothing happens when you click it, if it's moved; the clickable area stays where it should be.

One problem seems to be that the mouse coordinates from FlxG are relative to scrollfactor(0,0); maybe it would be good to have mouse coordinates relative to a layer or sprite accessible from that layer or sprite? Anyway, in my own version of the button class I changed this in the mouseover section. I also set the scrollfactor of the graphic and text to be (0,0) wherever made sense, and changed the overlapspoint so that it used the button rather than the off graphic.

These changes now work for fixed buttons, but still not for scrolling buttons. I think the reason is that I haven't understood how updatepositions works; the scrollfactor stuff above may be a red herring.

There's another problem I've been getting, which is that the default button graphic is a long white rectangle with no mouseover, and a small white square with mouseover. I don't think this is what's meant to happen, but haven't managed to fix it. One suspect is the createBitmap function in FlxG, which looks like it might have some typos in it.

**Comment by Objelisks** [comment]
I think this is happening because the FlxButton is assigning it's scrollfactor to the image and text when you add them, but doesn't update the children if you change the scrollfactor of the button after adding stuff to it. This could probably be fixed by using a getter/setter, but I dunno if you can override a regular variable with a getter/setter one.

**Comment by AdamAtomic** [comment]
the getter/setter for scrollFactor is tricky, because it's a point...so if you set scrollFactor.x, I don't think Flash can even capture that.  I'm gonna check it out regardless, thanks for the report!

**Comment by Pishtaco** [comment]
I originally thought that just setting the scrollFactor of the graphics and text to (0,0) would fix this, since they get moved by updatePositions anyway. But that seemed not to work.

**Comment by AdamAtomic** [comment]
Ok I had some just plain WRONG code in FlxCore.overlap and FlxSprite.overlap and I added a way for the FlxButton class to check for and update everyone's scrollfactors if the base button class's scrollfactor changes.  I did a quick HUD layer test in Mode and it seems to work great!  I'm gonna upload fixes in a few hours
