### ISSUE TITLE
Suggestion: FlxU.makeColor(r,g,b,a)

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#81]
For us programmers it might be trivial to shift bytes, mask them, OR them and get a color, but for some people I've met that are totally unfamiliar with it, it's a really hard task.

I suggest an addition to FlxU, which takes 4 unsigned integers (RGBA, the fourth optional) to make a "hex" number from regular R-G-B "as in game maker" colors.

The last parameter (alpha) could be a fractional from 0 to 1 to better fit with the workflow of flixel (as all alpha parameters take 0..1)

Regards

**Comment by brandoncash** [comment]
I approve of this.  So, naturally, I wrote it. ;)
I used the naming convention of other things in FlxU and went with getColor rather than makeColor, though.
It does some testing on Alpha, so it can be between 0 and 1 or between 0 and 255.

```
    /**
     * Generate an ARGB color.
     * 
     * @param   Red     The red component, between 0 and 255
     * @param   Green   The green component, between 0 and 255
     * @param   Blue    The blue component, between 0 and 255
     * @param   Alpha   How translucent the color should be, between 0 and 1
     * @return  The color as a uint
     */
    static public function getColor(Red:uint, Green:uint, Blue:uint, Alpha:Number=1.0):uint
    {
        return (((Alpha>1)?Alpha:(Alpha * 255)) & 0xFF) << 24 | (Red & 0xFF) << 16 | (Green & 0xFF) << 8 | (Blue & 0xFF);
    }
```

**Comment by AdamAtomic** [comment]
Nice, i like this a lot - making a note to drop this in later tonight!  I made some HSB stuff for trashpaint that might be nice to have too...definitely would be handy to be able to beef up the color tools!

**Comment by ghost** [comment]
:)
