### ISSUE TITLE
Suggestion: Taking care of mixed colouring/alpha conventions.

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#82]
It's confusing to have mixed color conventions. For example:
- To set the color and alpha of a sprite we use a RGB-hex (prop "color") and a opacity fractional range (prop "alpha")
- But to set the color to the background, we use bgColor (ARGB-hex), but if we forget to add the alpha channel (0xff000000) we don't get a background as they want, and for some people unfamiliar with Flixel internals/Flex (or older versions) it's <b>impossible</b> to find that as a bug.

This is confusing and avoidable. bgColor should OR a 0xff000000, and any other type of colouring should keep the same pattern to avoid confusions.

Regards
-Martín

**Comment by syndrome** [comment]
true, background color rarely needs zero alpha, if ever.
pick one of these two solutions:

1) background color value is checked for alpha (if it's 0, a default 0xff alpha is used instead)
if((bgColor & 0xff000000) == 0) bgColor |= 0xff000000;

2) background color alpha is a separate argument (color as uint, alpha as Number)
bgColor = (((0xff \* alpha) & 0xff) << 24) | color;

**Comment by ghost** [comment]
I don't think transparent background even works on most browsers, so I believe that a setter that drops the alpha part (color & 0xff000000) will do the trick :)

Solution (1) has weird "backward-compatible" semantics. It might seem like a good solution but it's just "masking" the real problem: Newcommers will also get confused.
I'd go for (2).

Regards

**Comment by syndrome** [comment]
I'm for (2) as well, it's much cleaner in the long run. (1) is more like a cover-up, a hidden feature yelling "undocumented".

btw, transparent background does work (in the leading browsers), however, the html environment must be properly conditioned before embedding. it is also, much slower to render (therefore, unsuitable for flixel games).

**Comment by AdamAtomic** [comment]
FlxSprite only has alpha split out because its frequently used on its own terms - anything else that uses color is stored as ARGB i think... you can also pass ARGB to sprite, it will just ignore the A you passed in favor of the existing value is all.  good discussion though!

**Comment by ghost** [comment]
Exactly, that's what I call a mixup of semantics, hehe.

I brought up this topic because I was in a jam making some games and, unexpectedly, this coloring thing and the lack of a "makeColor(r,g,b,a)" function was a hard obstacle for some people that came from other technologies.

Besides what is "anything else"? FlxSprite and FlxText both work with separate color/alpha :)
I think it's better to have them split, I'm into that, but have them split everywhere to maintain coherence among the API (which is really important)

Best regards!
