### ISSUE TITLE
Typo in FlxObject's "solid" doc

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#83]
<pre>
        /**
         * If an object is dead, the functions that automate collisions will skip it (see <code>FlxG.overlapArrays()</code> and <code>FlxG.collideArrays()</code>).
         */
</pre>

```
    public var solid:Boolean;
```

I think that's outdated. A tentative replacement could be

<pre>
        /**
         * If an object is not solid, the functions that automate collisions will skip it (see <code>FlxU.overlaps()</code> and <code>FlxU.collides()</code>).
         */
</pre>

regards

**Comment by AdamAtomic** [comment]
hmm, that is from a pretty old version, was corrected in one of the beta or dev builds a while ago!  thanks tho :)

**Comment by ghost** [comment]
Sorry!
