### ISSUE TITLE
Flex SDK 4.0.0.14159

### ISSUE THREAD

**Issue by RobertCGouge** [AdamAtomic/flixel#84]
in FlxGame, the lines covering EmbedFonts need to have the embedAsCFF="false" removed completely from the Flex 4 SDK params for fonts to work

**Comment by brandoncash** [comment]
That line is most definitely still needed for me, and I'm using the same build.

**Comment by RobertCGouge** [comment]
Not the whole line, just the embedAsCFF param.  It errors out saying embedAsCFF isn't supported.  That is what I am experiencing.  I'll look into it

**Comment by brandoncash** [comment]
Yes, it is still needed for me.

**Comment by Epic428** [comment]
I just tried creating the hello world project and it wouldn't compile due to that error. Removing that parameter allowed it to compile correctly. Also when viewing the file in FD it was showing a syntax error on that line because of that parameter.

**Comment by AdamAtomic** [comment]
I'm not sure what version of Flex 4 SDK i'm using, but I definitely require the embedAsCFF still as well - if you get any more data on this i'll re-open and address it!  thanks guys

**Comment by Epic428** [comment]
for some reason when i did hello world it gave error, but then when I did another project it worked without embed. lol then i put it back in and it still worked. so not sure what exactly is wrong with it. might be something someone could play with and test.

**Comment by RobertCGouge** [comment]
I have noticed that the error is random, so there must be a problem elsewhere.
