### ISSUE TITLE
[v2.35] Same value for maxVelocity.x and y don't make a perfect diagonal movement

### ISSUE THREAD

**Issue by WingEraser** [AdamAtomic/flixel#85]
I updated flixel from 2.23 to 2.35.
I created an object with maxVelocity.x = maxVelocity.y = 50. This will make a diagonal movement with same speed on x and y coordinate. However, it seems that maxVelocity.x called more than once. I tested this in a new project. To get the correct movement, maxVelocity.x has to be set with the value of 33.
Sorry for the bad English ^^.

**Comment by AdamAtomic** [comment]
what values are you using for acceleration and velocity?  maxVelocity is just a way of capping acceleration... do you have an example online?  Let me know if you have any more info, thanks!

**Comment by WingEraser** [comment]
First I though there something wrong with FP 10.1. Then I think again, I always made my game in FP 10.1. So I did some tests again in FP10 and 10.1.

The result:
The left Bomb got MaxVelocity.x and y = 50.
The right Bomb got MaxVelocity.x = 33 and y = 50.
There is no acceleration value set.
The code would look like this:

... update(): void
velocity.x -= maxVelocity.x;
velocity.y = maxVelocity.y;
super.update();

Strangely, the right bomb got the right movement and the left bomb is the velocity.x quicker.

http://wingeraser.nl/flixel/Velocity%2010.1.0.swf
http://wingeraser.nl/flixel/Velocity%2010.0.0.swf

I put the project file on my server. 
http://wingeraser.nl/flixel/Velocity.rar

I hope this help you to understand the problem.

**Comment by WingEraser** [comment]
My bad, MaxVelocity doesn't work with negative numbers.
