### ISSUE TITLE
Mouse jumps when clicked

### ISSUE THREAD

**Issue by aschearer** [AdamAtomic/flixel#86]
This happens on my Macbook running Leopard. Tested with the latest version of Flixel (commit  b9fe56451f3a8bd0d3856fc4a5ab44ff90255506). Happens for my swf and ones I've found from the wiki.

Repro steps:
- Navigate to http://playground.brandoncash.net/island/
- Click somewhere on the game to spread sand
- Notice the cursor jumping up and to the left

Expected results: The cursor shouldn't move at all.
Observed results: Cursor jumps out of position on click and then returns to normal.

**Comment by AdamAtomic** [comment]
haven't been able to replicate the behavior, are you running latest flash player and all that good stuff?
