### ISSUE TITLE
[v2.41] Fix small annoying erros which makes FDT users happy

### ISSUE THREAD

**Issue by WingEraser** [AdamAtomic/flixel#87]
FlxButton
179
public function get on():Boolean
{
    return _onToggle;
    _onToggle = On; // Delete this line.
}

FlxGame
498
if(_frame != null)
{
        ...
    var bmp:Bitmap = new _frame; // new _frame();
        ...
}

FlxSound
100
public function loadEmbedded(EmbeddedSound:Class, Looped:Boolean=false):FlxSound
{       ...
    _sound = new EmbeddedSound; // new EmbeddedSound();
    ...
}

I just want to offer a help if possible.

**Comment by AdamAtomic** [comment]
ok all set, thanks :D
