### ISSUE TITLE
Horrible Garbage Collection

### ISSUE THREAD

**Issue by hamedn** [AdamAtomic/flixel#89]
For some reason, classes FlxPoint and FlxRect won't be garbage collected. They keep on filling up my program's memory until it is seriously lagging flash player.

**Comment by AdamAtomic** [comment]
Can you tell me any more about where these are getting instantiated or how to track this stuff down?  thanks!

**Comment by hamedn** [comment]
Whoops, it was all just cause of my stupidity...

Just added this line to the beginning of the nextLevel() function:

_gravMap.kill()
_gravMap = null;
_gravMap = new FlxTilemap()
_solidMap.kill()
_solidMap = null;
_solidMap = new FlxTilemap()
lyrMaps.members.length = 0;

(_solidMap and _gravMap) are just the tilemaps my game uses.

What is strange though is that this problem just started occuring when I updated

**Comment by AdamAtomic** [comment]
probably was a change to the way tilemap stores stuff or something?  not sure :)  thanks for checking that out for me!
