### ISSUE TITLE
Separate sprite width/height and collision width/height

### ISSUE THREAD

**Issue by Objelisks** [AdamAtomic/flixel#9]
I've got a problem in my current game where there is a 16x16 tilemap, and a few 16x16 characters. The characters can't fall through a 16x16 hole in the ground because of rounding. I think that collision width and height should be separated out to their own variables so that the sprites could have 16x16 images, but a collision box of 14x16 or something, but I'm not sure how to go about this myself. I've got a solution right now, but it is pretty messy.

**Comment by AdamAtomic** [comment]
Yea this has been in for ages :)  you can check mode for an example, but the most important variable for this is called 'offset'.  It's the offset of hte graphic from the collision hull.  The basic process you need to do is load/create your graphic, then manually set the width and height, then adjust offset.x and offset.y until the graphic and the object are arranged the way you want :)
