### ISSUE TITLE
Flash Player 10.1 + Advanced Render = BIG problems

### ISSUE THREAD

**Issue by PaulGene** [AdamAtomic/flixel#90]
Hi,

I recently installed Flash Player 10.1 and instantly noticed a huge performance drop on my current project.

A lot of the sprites in my project are rotated, and i narrowed the problem down to FlxG.buffer.draw() in FlxSprite's renderSprite() method. For some reason its causing memory to fluctuate, which in turn is probably causing the performance drop as GC keeps getting called.

As an example I've modified FlxInvaders so it always uses advanced render, and added system memory display to the Flixel console.

I've tested this on four computers now and get the same result each time.

My specs: Windows 7, single core Athlon 3800+, 2.5gb RAM

My Results:

Flash Player 10 : stable 60fps, memory is totally solid at 4mb, everything feels nice and smooth.

Flash Player 10.1 : unstable 20-25fps, memory seems to loop from about 10mb to 50mb then GC gets called, everything feels laggy and unstable including keyboard input.

Here is the example http://www.swfcabin.com/open/1276734228 (put up the console to check memory usage)

I've tested this on the following browsers with very similar results: IE 8 / Chrome 5 / Firefox 3.6 / Safari 4

It will be interesting to see if everyone has the same problem on Flash Player 10.1, this could even be a Flash Player bug rather than a Flixel problem.

**Comment by jon914** [comment]
I notice this too, but not to as drastic a degree as Paul has.

The FPS breakdown shows that the "Flash" portion of the timestep is taking up noticeably more time in 10.1 than in 10.0.

**Comment by AdamAtomic** [comment]
haha that is really messed up - i wonder what they changed that its so messed up?  i don't think i instantiate stuff during draw calls anymore, i use all statically allocated stuff...sounds like they're allocating internally during draw?  it's hard to say :(

**Comment by jon914** [comment]
Maybe check with Chevy to see if he's also noticing this in his library?

**Comment by PaulGene** [comment]
I've just tested this with 8bitrockets examples http://www.8bitrocket.com/newsdisplay.aspx?newspage=6765

And it shows exactly the same results, i cant believe Adobe missed a bug this big.

Have you got any contacts at Adobe Adam? this needs sorting ASAP

**Comment by jon914** [comment]
If Adam doesn't, I actually do have a couple I could reach out to. They aren't directly on the player team, but they work on the Flex API, so it's close enough to pass the word.

Edit: Doesn't the guy who runs senocular.com (Trevor McCauley) work on the Flash player team? You ought to talk directly to him.

**Comment by PaulGene** [comment]
I've tried contacting loads of flash insiders, haven't had a single reply. I guess they are all too important to talk to the likes of me :@

I'll post the problem on Adobe's bug tracking website (which looks like a total nightmare)  as soon as i get some free, which will be god knows when.

**Comment by PaulGene** [comment]
Man, it was seriously hard explaining that! it probably makes no sense https://bugs.adobe.com/jira/browse/FP-4812

**Comment by PaulGene** [comment]
A work around has been found https://bugs.adobe.com/jira/browse/FP-4812

**Comment by AdamAtomic** [comment]
i think whatever this thing was has gone away in the most recent FP, but let me know if that's NOT the case!
