### ISSUE TITLE
[2.43] FlxTilemap: lines 819 and 820 are wrong.

### ISSUE THREAD

**Issue by jeanpier** [AdamAtomic/flixel#91]
819 var w:uint = bitmapData.width;
820 var h:uint = bitmapData.height;

This is wrong and gives error when compiling.

Should be:
819 var w:uint = layout.width;
820 var h:uint = layout.height;

**Comment by AdamAtomic** [comment]
man flxtilemap on the beta branch was REALLY messed up (still), kind of embarrassed...pushing up a fix now
