### ISSUE TITLE
[2.41] FlxU.getAngle: if arguments are zero, returns NaN

### ISSUE THREAD

**Issue by WeslomPo** [AdamAtomic/flixel#92]
For example, FlxU.getAngle(x-mouseX,y-mouseY), where x,y == mouseX,mouseY

It my function (i take name from GameMaker program), created with code from original "getAngle":

{
static public function pointDirection(X:Number,Y:Number,X2:Number,Y2:Number):Number
        {
            X = X2 - X;
            Y = Y2 - Y;
            var c1:Number = 3.14159265 / 4;
            var c2:Number = 3 \* c1;
            var ay:Number = (Y < 0)?-Y:Y;
            var angle:Number = 0;
            if (X >= 0)
                angle = c1 - c1 \* ((X - ay) / (X + ay)); // Devide by zero
            else
                angle = c2 - c1 \* ((X + ay) / (ay - X)); // Devide by zero
            if (isNaN(angle)) return 0; // It my solution for this error
            return (((Y < 0)? (angle):6.2831853-angle) \* 57.2957796) % 360
            //Dont panic, just 0..360 value
        };
}

Sorry for my ugly English, and it's my first Issue :)

**Comment by freelancebrandon** [comment]
I can confirm this issue.  My fix at the moment is to check if X and Y are zero before calling the function.

**Comment by AdamAtomic** [comment]
cool, I have to work on these functions later today anyways, so I made a note to test this case!  thanks dudes

**Comment by CoderBrandon** [comment]
My quick fix in FlxU.getAngle first line before anything happens:
```if (X == 0 && Y == 0) return 0;

```
```

**Comment by AdamAtomic** [comment]
yea that's the ticket, just dropped that in :)
