### ISSUE TITLE
FlxObject.overlaps() with wrong behaviour on sprites with custom offset/width/height

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#94]
overlaps() is overriding the real "collision width/height" with the frame (image) size.
What it should do is fix the position using the offset instead.

Here's the fix:
<code>
        public function overlaps(Object:FlxObject):Boolean
        {
            getScreenXY(_point);
            var tx:Number = _point.x;
            var ty:Number = _point.y;
            var tw:Number = width;
            var th:Number = height;
            if(this is FlxSprite)
            {
                var ts:FlxSprite = this as FlxSprite;
                /_tw = ts.frameWidth;
                th = ts.frameHeight;_/
                tx += ts.offset.x;
                ty += ts.offset.y;
            }
            Object.getScreenXY(_point);
            var ox:Number = _point.x;
            var oy:Number = _point.y;
            var ow:Number = Object.width;
            var oh:Number = Object.height;
            if(Object is FlxSprite)
            {
                var os:FlxSprite = Object as FlxSprite;
                /_ow = os.frameWidth;
                oh = os.frameHeight;_/
                ox += os.offset.x;
                oy += os.offset.y;
            }

```
        if((ox <= tx-ow) || (ox >= tx+tw) || (oy <= ty-oh) || (oy >= ty+th))
            return false;


        return true;
    }
```

</code>

Best regards

**Comment by ghost** [comment]
Guys, please comment. I think this is important.

**Comment by jagt** [comment]
Thanks a lot man, I was just guessing there's something wrong with this and found this one.

**Comment by ghost** [comment]
I'm glad it helped!

I think now with quad-trees code and all this function doesn't get called often.

**Comment by clayton-grey** [comment]
I found this just now! Forgot to look here. This would be good to fold in along with:

http://github.com/AdamAtomic/flixel/issues/#issue/101

...which affects overlaps() on FlxTileMaps.

**Comment by AdamAtomic** [comment]
yea i'm sorry about that dudes, that stuff was a big mess.  I did a pass on it earlier in the v2.50 overhaul, and just did ANOTHER pass on it a couple hours ago.  the basic approach now is:

FlxObject.overlapsPoint() uses world space points and takes a parameter for world space/screenspace compare
FlxObject.overlaps() takes a parameter for either world space or screen space (takes scroll factor into account)
FlxSprite.overlaps() is not custom
FlxSprite.getScreenXY() is no longer custom either
FlxSprite.pixelOverlapsPoint() is a new function that does a per-pxiel screen space check against a world space point

hopefully it should clarify/simplify this whole confusing thing!
