### ISSUE TITLE
FlxSprite.calcFrame breaks if there is an animation callback but no animations. [w/FIX]

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#95]
<pre>
[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.
Fault, calcFrame() at FlxSprite.as:662
</pre>

It breaks because _curAnim is null.

Fix:

<pre>
if(_callback != null) _callback(_curAnim ? _curAnim.name : null,_curFrame,_caf);
</pre>

**Comment by AdamAtomic** [comment]
ah good catch, will go out in the next push :) thanks!
