### ISSUE TITLE
FlxG.showBounds = true shows bounding Boxes that are inconsitent with the collision detection

### ISSUE THREAD

**Issue by datorum** [AdamAtomic/flixel#96]
I noticed that the bounding boxes that are shown, when I call FlxG.showBounds = true; are inconsistent with the collision detection.
Furthermore, the community told me that bounding boxes are not rotated, whereas the bounding boxes are drawn rotated.
Yet, the 90 degree rotation of a big sprite with a small bounding box seems to draw the bounding box incorrectly. Whereas the width & height are drawn correctly.
version 2.35 [release]

```
        super(xPos,yPos);
        health = 1000;
        loadGraphic(ImageCarrier,false,true,150,60);
        width = 40; //from 150 to 40
        height = 25; // from 60 to 25
        offset.x = 75;
        offset.y = 30;          
        angle = -90; //with angle 0 the box is drawn correctly

        solid = true;
        maxAngular = 20;
        angularDrag = 200;
        maxThrust = 10;
        drag.x = 2;
        drag.y = 2;
        thrust = -10;
        velocity.x = 0;
        velocity.y = 0;
```

**Comment by AdamAtomic** [comment]
yea the old bounding box display system was messed up.  v2.50 is more accurate, and only shows squares (like its supposed to!)
