### ISSUE TITLE
Suggestion: preCollide to return a boolean value that aborts solveX/YCollision()

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#97]
If preCollide can return a boolean that aborts the collision checks before they're done,  then customizations to collisions can be made.
For example: You shoot a laser that changes color over time, and only want to destroy objects of the same color, otherwise pass-thru them. This upgrade could easily solve it:

<pre>
override preCollide(Object...) { return (Object.color == this.color); }
</pre>

What do you guys think?
Btw, is it OK for me to post suggestions as Issues? Is another place for this?

Here's the topic:
http://flixel.org/forums/index.php?topic=1932.msg12071#msg12071

**Comment by AdamAtomic** [comment]
this is a fine place to suggest things!  however preCollide() was removed in v2.50, I'd recommend using FlxG.overlap() with a Notify callback I think to accomplish what you're talking about here...
