### ISSUE TITLE
 Button sweep over

### ISSUE THREAD

**Issue by UberGeorge** [AdamAtomic/flixel#98]
The button sweep over problem first brought up back in July/2009 by nitram_cero (2bam) still hasn't been fixed.

If you have multiple buttons on screen and you click on one of them without releasing the mouse button, you can then move the mouse pointer over to another button, release the mouse button there, and that button responds as if it was the one clicked.

This is the thread where it was first brought up: http://flixel.org/forums/index.php?topic=207.0

**Comment by AdamAtomic** [comment]
v2.50 buttons should no longer have this lame issue!
