### ISSUE TITLE
FlxG.createBitmap "Unique" param never used. Problems with FlxG.fade/flash arise from this [with solution]

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#99]
"Unique" param wasn't respected when creating bitmaps. This made FlxG.flash fail because it shared a BitmapData with FlxG.fade (I'm assuming).

I have a new proposition for FlxG.createBitmap.
Changes:
-Unique is used (currently it's not, fixed an invalid if)

-It uses a private static unique-id counter to avoid having to "find an unique id" each call to createBitmap

Here's the fixed code:

<pre>
        static private var _bmpUniqueID:uint = 0;
        
        static public function createBitmap(Width:uint, Height:uint, Color:uint, Unique:Boolean=false, Key:String=null):BitmapData
        {
            var key:String = Key;
            if(key == null)
            {
                key = Width+"x"+Height+":"+Color;
                if(Unique)
                    key += "/" + (_bmpUniqueID++);
            }
            if(!checkBitmapCache(key))
                _cache[key] = new BitmapData(Width,Height,true,Color);
            return _cache[key];
        }
</pre>

OLD code for reference:

<pre>
        static public function createBitmap(Width:uint, Height:uint, Color:uint, Unique:Boolean=false, Key:String=null):BitmapData
        {
            var key:String = Key;
            if(key == null)
            {
                key = Width+"x"+Height+":"+Color;
                if(Unique && (_cache[key] != undefined) && (_cache[key] != null))
                {
                    //Generate a unique key
                    var inc:uint = 0;
                    var ukey:String;
                    do { ukey = key + "/" + inc++;
                    } while((_cache[ukey] != undefined) && (_cache[ukey] != null));
                    key = ukey;
                }
            }
            if(!checkBitmapCache(key))
                _cache[key] = new BitmapData(Width,Height,true,Color);
            return _cache[key];
        }
        
</pre>

**Comment by AdamAtomic** [comment]
flash and fade seem ok i think?  let me know if this is still a problem in v2.50 - the logic behind the old code is that it will only generate a new unique key if the default key isn't already unique.

**Comment by AdamAtomic** [comment]
AH HA i see what this refers to now!  I will address this in the next push :)
